import type { TechnologyPack } from './types'

export const AWS_PACK: TechnologyPack = {
  id: 'aws',
  label: 'AWS',
  serves: ['aws', 'azure', 'gcp'],
  categories: {
    architecture: {
      prompt:
        'Describe the cloud architecture you built or ran: accounts, network layout, compute, data stores, how it stayed available across zones, and why it was shaped that way.',
      concepts: [
        [
          'Account and environment structure',
          [
            'multi-account',
            'organization',
            'landing zone',
            'account per',
            'control tower',
            'subscription',
            'project',
          ],
          'How were environments and teams separated?',
          2,
        ],
        [
          'Compute choice and scaling',
          ['ec2', 'autoscaling', 'auto scaling', 'ecs', 'eks', 'lambda', 'fargate', 'scale'],
          'What ran the workload and how did it scale?',
          3,
        ],
        [
          'Data stores and durability',
          ['rds', 's3', 'dynamodb', 'backup', 'replica', 'multi-az', 'snapshot', 'durability'],
          'Where did the data live and how was it protected?',
          3,
        ],
        [
          'Availability across zones and regions',
          [
            'availability zone',
            'multi-az',
            'multi-region',
            'failover',
            'disaster recovery',
            'rto',
            'rpo',
            'redundan',
          ],
          'What survived the loss of a zone?',
          3,
        ],
        [
          'Cost awareness',
          ['cost', 'reserved', 'savings plan', 'spot', 'right-siz', 'budget', 'tagging'],
          'How did you keep it affordable?',
          1,
        ],
      ],
    },
    networking: {
      prompt:
        'Describe the cloud network: VPC layout, subnets, routing, how traffic entered and left, how private services were reached, and how you diagnosed a connection that failed.',
      concepts: [
        [
          'VPC, subnets and routing',
          [
            'vpc',
            'subnet',
            'route table',
            'cidr',
            'public subnet',
            'private subnet',
            'internet gateway',
          ],
          'How was the network divided and routed?',
          3,
        ],
        [
          'Entry points and load balancing',
          [
            'alb',
            'nlb',
            'load balancer',
            'cloudfront',
            'route 53',
            'route53',
            'api gateway',
            'waf',
          ],
          'How did users reach the workload?',
          2,
        ],
        [
          'Egress and private access',
          [
            'nat gateway',
            'vpc endpoint',
            'privatelink',
            'transit gateway',
            'peering',
            'vpn',
            'direct connect',
          ],
          'How did private resources reach services without public exposure?',
          2,
        ],
        [
          'Security groups and NACLs',
          ['security group', 'nacl', 'ingress', 'egress', 'stateful', 'stateless', 'flow logs'],
          'What decided whether a packet was allowed?',
          3,
        ],
        [
          'Debugging reachability',
          [
            'reachability analyzer',
            'flow logs',
            'traceroute',
            'route',
            'dns',
            'curl',
            'telnet',
            'security group',
          ],
          'How did you find where a connection stopped?',
          2,
        ],
      ],
    },
    security: {
      prompt:
        'What security controls did you apply in that cloud environment: identity, permissions, data protection, network exposure, and how you would notice misuse?',
      concepts: [
        [
          'IAM and least privilege',
          [
            'iam',
            'least privilege',
            'role',
            'policy',
            'assume role',
            'scp',
            'permission boundary',
            'sso',
            'mfa',
          ],
          'How were permissions granted, and how narrow were they?',
          3,
        ],
        [
          'Encryption and key management',
          ['kms', 'encrypt', 'at rest', 'in transit', 'tls', 'customer managed key', 'envelope'],
          'What was encrypted, and who controlled the keys?',
          2,
        ],
        [
          'Secrets handling',
          [
            'secrets manager',
            'parameter store',
            'rotation',
            'vault',
            'no hardcoded',
            'credentials',
          ],
          'Where did credentials live?',
          2,
        ],
        [
          'Exposure and guardrails',
          [
            'public bucket',
            's3 block public',
            'security hub',
            'config rule',
            'guardrail',
            'scp',
            'waf',
            'inspector',
          ],
          'What stopped an accidental public exposure?',
          3,
        ],
        [
          'Detection and audit',
          ['cloudtrail', 'guardduty', 'audit', 'config', 'alert', 'siem', 'log'],
          'How would you know an access key was abused?',
          2,
        ],
      ],
    },
    observability: {
      prompt:
        'How did you monitor the cloud workloads: metrics, logs, traces, alarms, and the signals that decided whether you were healthy?',
      concepts: [
        [
          'Metrics and alarms',
          [
            'cloudwatch',
            'alarm',
            'metric',
            'threshold',
            'composite alarm',
            'datadog',
            'prometheus',
            'sns',
          ],
          'Which alarms mattered and where did they go?',
          3,
        ],
        [
          'Logs and queries',
          [
            'cloudwatch logs',
            'log insights',
            'elk',
            'opensearch',
            'centralised',
            'centralized',
            'log group',
            'retention',
          ],
          'How did you search logs across services?',
          2,
        ],
        [
          'Tracing and request flow',
          ['x-ray', 'xray', 'tracing', 'opentelemetry', 'correlation id', 'span'],
          'How did you follow a request through the services?',
          1,
        ],
        [
          'Service-level objectives',
          ['slo', 'sli', 'availability', 'latency', 'error budget', 'burn rate', 'golden signal'],
          'What were you promising and how did you measure it?',
          3,
        ],
        [
          'Health and limits',
          ['health check', 'service quota', 'throttl', 'limits', 'capacity', 'synthetic', 'canary'],
          'How did you see limits coming?',
          2,
        ],
      ],
    },
    troubleshooting: {
      prompt:
        'An application in the cloud suddenly cannot reach its database, or requests start failing intermittently. Walk me through how you narrow it down.',
      concepts: [
        [
          'Scope and recent change',
          [
            'what changed',
            'recent change',
            'deploy',
            'cloudtrail',
            'scope',
            'which',
            'started',
            'affected',
          ],
          'What do you establish before choosing a theory?',
          3,
        ],
        [
          'Network layers in order',
          ['security group', 'route table', 'nacl', 'dns', 'subnet', 'endpoint', 'flow logs'],
          'Which network layers do you rule out, in what order?',
          3,
        ],
        [
          'Identity and permissions',
          ['iam', 'access denied', 'permission', 'role', 'policy', 'token expired', 'assume'],
          'What if the network is fine but calls are refused?',
          2,
        ],
        [
          'Capacity, limits and throttling',
          [
            'throttl',
            'quota',
            'limit',
            'connection pool',
            'cpu credits',
            'iops',
            'max connections',
            'burst',
          ],
          'What if the system is simply out of something?',
          2,
        ],
        [
          'Dependency health',
          [
            'health check',
            'rds',
            'failover',
            'replica',
            'maintenance',
            'status page',
            'service health',
          ],
          'Could the platform itself be having a problem?',
          2,
        ],
      ],
    },
    'trade-offs': {
      prompt:
        'What trade-offs did you make in that cloud design: virtual machines versus containers versus serverless, managed versus self-run, cost versus resilience, single versus multi-region?',
      concepts: [
        [
          'Compute model',
          [
            'ec2',
            'container',
            'lambda',
            'serverless',
            'fargate',
            'cold start',
            'control',
            'operational overhead',
          ],
          'Why that compute model and not another?',
          3,
        ],
        [
          'Managed versus self-managed services',
          [
            'managed',
            'rds',
            'self-hosted',
            'aurora',
            'lock-in',
            'operational burden',
            'cost of managed',
          ],
          'What did you hand to the provider and what did that cost?',
          2,
        ],
        [
          'Cost versus resilience',
          ['cost', 'redundan', 'multi-az', 'reserved', 'spot', 'budget', 'idle', 'standby'],
          'How much resilience was worth paying for?',
          3,
        ],
        [
          'Region strategy',
          [
            'multi-region',
            'single region',
            'dr',
            'active-active',
            'latency',
            'complexity',
            'data residency',
            'failover',
          ],
          'Why one region, or why more than one?',
          2,
        ],
        [
          'Vendor lock-in',
          ['lock-in', 'portab', 'multi-cloud', 'terraform', 'open source', 'abstraction', 'exit'],
          'How tied to the provider were you, on purpose?',
          1,
        ],
      ],
    },
    incidents: {
      prompt:
        'Describe a cloud incident: a zone or service degradation, a bad IAM change, an exposed bucket or a cost explosion. How was it detected, mitigated, communicated and prevented?',
      concepts: [
        [
          'Detection',
          [
            'alarm',
            'alert',
            'paged',
            'health dashboard',
            'customers',
            'cost anomaly',
            'guardduty',
            'noticed',
          ],
          'How did you first learn about it?',
          2,
        ],
        [
          'Mitigation',
          [
            'failover',
            'rollback',
            'revoke',
            'scale',
            'shift traffic',
            'disable',
            'restore',
            'quarantine',
          ],
          'What did you do first to contain it?',
          3,
        ],
        [
          'Cause',
          [
            'root cause',
            'misconfig',
            'iam change',
            'quota',
            'az',
            'deployment',
            'runaway',
            'public',
          ],
          'What was the underlying cause?',
          2,
        ],
        [
          'Communication',
          [
            'status page',
            'stakeholder',
            'incident commander',
            'customers',
            'update',
            'escalat',
            'support case',
          ],
          'Who was kept informed, including the provider?',
          2,
        ],
        [
          'Prevention',
          [
            'postmortem',
            'guardrail',
            'scp',
            'budget alert',
            'game day',
            'chaos',
            'runbook',
            'automation',
            'least privilege',
          ],
          'What changed to prevent a repeat?',
          3,
        ],
      ],
    },
  },
}
