import type { TechnologyPack } from './types'

export const CICD_PACK: TechnologyPack = {
  id: 'ci-cd',
  label: 'CI/CD',
  serves: ['ci-cd', 'jenkins', 'github-actions', 'gitlab', 'argocd'],
  categories: {
    architecture: {
      prompt:
        'Describe the delivery pipeline you built: stages from commit to production, where artifacts lived, how environments were promoted, and why it was designed that way.',
      concepts: [
        [
          'Pipeline stages and gates',
          ['build', 'test', 'lint', 'stage', 'gate', 'approval', 'deploy', 'quality gate'],
          'What happened between a commit and production?',
          3,
        ],
        [
          'Artifacts and versioning',
          ['artifact', 'registry', 'immutable', 'version', 'tag', 'build once', 'promote', 'sha'],
          'Was what you tested the same thing you shipped?',
          3,
        ],
        [
          'Runners and build infrastructure',
          [
            'runner',
            'agent',
            'executor',
            'self-hosted',
            'ephemeral',
            'autoscal',
            'cache',
            'parallel',
          ],
          'Where did the builds run?',
          2,
        ],
        [
          'Deployment strategy',
          [
            'rolling',
            'blue-green',
            'blue green',
            'canary',
            'feature flag',
            'progressive',
            'gitops',
            'argo',
          ],
          'How did a release reach users safely?',
          3,
        ],
        [
          'Pipeline as code',
          [
            'pipeline as code',
            'jenkinsfile',
            'yaml',
            'shared library',
            'template',
            'reusable workflow',
            'version controlled',
          ],
          'How was the pipeline itself maintained?',
          1,
        ],
      ],
    },
    networking: {
      prompt:
        'How did your pipeline reach what it needed over the network: build runners to registries and private systems, deployments into private environments, webhooks and egress controls?',
      concepts: [
        [
          'Runner reachability to private targets',
          [
            'private network',
            'vpn',
            'self-hosted runner',
            'bastion',
            'peering',
            'agent inside',
            'vpc',
          ],
          'How did the pipeline reach a private environment?',
          3,
        ],
        [
          'Registry and dependency access',
          [
            'registry',
            'proxy',
            'mirror',
            'cache',
            'artifactory',
            'nexus',
            'dependency',
            'rate limit',
          ],
          'How did builds fetch dependencies reliably?',
          2,
        ],
        [
          'Webhooks and triggers',
          ['webhook', 'trigger', 'polling', 'event', 'callback', 'endpoint', 'github app'],
          'How did a push start a build?',
          2,
        ],
        [
          'Egress control',
          ['egress', 'allowlist', 'allow list', 'firewall', 'proxy', 'restricted', 'outbound'],
          'What could a build reach on the internet?',
          2,
        ],
      ],
    },
    security: {
      prompt:
        'How did you secure the delivery pipeline: secrets, deployment credentials, who could change the pipeline, third-party dependencies and the integrity of what was shipped?',
      concepts: [
        [
          'Secrets in pipelines',
          [
            'secret',
            'vault',
            'masked',
            'credential',
            'oidc',
            'short-lived',
            'environment secret',
            'not in the repo',
          ],
          'How did the pipeline get credentials without exposing them?',
          3,
        ],
        [
          'Least-privilege deploy access',
          [
            'least privilege',
            'deploy role',
            'separate',
            'scoped',
            'assume role',
            'service account',
            'per environment',
          ],
          'What could the pipeline do to production?',
          3,
        ],
        [
          'Protected branches and approvals',
          [
            'branch protection',
            'code review',
            'approval',
            'four eyes',
            'codeowners',
            'required check',
            'manual gate',
          ],
          'Who could change what reached production?',
          2,
        ],
        [
          'Scanning and supply chain',
          [
            'sast',
            'dast',
            'dependency scan',
            'trivy',
            'snyk',
            'sonar',
            'sbom',
            'signed',
            'cosign',
            'pinned action',
          ],
          'How did you catch vulnerable code or dependencies?',
          2,
        ],
        [
          'Runner isolation',
          [
            'ephemeral',
            'isolat',
            'untrusted',
            'fork',
            'self-hosted risk',
            'sandbox',
            'clean workspace',
          ],
          'Could one build affect another?',
          2,
        ],
      ],
    },
    observability: {
      prompt:
        'How did you measure and monitor delivery itself: build health, lead time, failures, and knowing what a deployment did to production?',
      concepts: [
        [
          'Delivery metrics',
          [
            'dora',
            'lead time',
            'deployment frequency',
            'change failure',
            'mttr',
            'build time',
            'cycle time',
          ],
          'What numbers told you delivery was healthy?',
          3,
        ],
        [
          'Deploy markers and correlation',
          [
            'deploy marker',
            'annotation',
            'release tag',
            'version label',
            'correlate',
            'change event',
            'dashboard',
          ],
          'How did you connect a regression to a release?',
          3,
        ],
        [
          'Flaky tests and pipeline health',
          ['flaky', 'retry', 'quarantine', 'failure rate', 'queue time', 'slow', 'trend'],
          'How did you handle unreliable tests?',
          2,
        ],
        [
          'Notifications and ownership',
          ['notification', 'slack', 'alert', 'owner', 'broken build', 'on-call', 'status check'],
          'Who found out when the pipeline broke?',
          1,
        ],
      ],
    },
    troubleshooting: {
      prompt:
        'A pipeline that passed yesterday now fails, or a deploy succeeds but the service is broken. Walk me through how you find the cause.',
      concepts: [
        [
          'What changed',
          [
            'what changed',
            'diff',
            'recent commit',
            'dependency',
            'bisect',
            'base image',
            'runner image',
            'config change',
          ],
          'What do you compare first?',
          3,
        ],
        [
          'Logs, reproduction and isolation',
          ['logs', 'reproduce', 'locally', 'rerun', 'isolate', 'debug', 'ssh into', 'verbose'],
          'How do you get from a red build to a reproducible cause?',
          3,
        ],
        [
          'Environment and caching',
          [
            'cache',
            'stale',
            'environment',
            'version',
            'runner',
            'cleanup',
            'clean build',
            'tool version',
          ],
          'Why might the same code behave differently?',
          2,
        ],
        [
          'Flaky versus real failures',
          ['flaky', 'intermittent', 'race', 'timeout', 'order', 'resource', 'rerun'],
          'How do you tell flakiness from a real regression?',
          2,
        ],
        [
          'Post-deploy verification and rollback',
          ['smoke test', 'health check', 'rollback', 'verify', 'canary', 'post-deploy', 'revert'],
          'How do you tell a bad deploy and undo it?',
          3,
        ],
      ],
    },
    'trade-offs': {
      prompt:
        'What trade-offs did you make in your delivery approach: trunk-based versus branching, speed versus thoroughness, hosted versus self-hosted runners, push versus pull (GitOps), monorepo versus many?',
      concepts: [
        [
          'Branching and release model',
          [
            'trunk-based',
            'trunk based',
            'gitflow',
            'release branch',
            'feature branch',
            'feature flag',
            'merge',
          ],
          'How did code reach the main line?',
          2,
        ],
        [
          'Speed versus confidence',
          [
            'fast feedback',
            'test pyramid',
            'parallel',
            'slow',
            'thorough',
            'smoke',
            'nightly',
            'risk',
          ],
          'What did you not run on every commit, and why?',
          3,
        ],
        [
          'Hosted versus self-hosted infrastructure',
          [
            'hosted',
            'self-hosted',
            'cost',
            'maintenance',
            'control',
            'security',
            'saas',
            'jenkins',
          ],
          'Who ran the build machines and why?',
          2,
        ],
        [
          'Push versus pull deployment',
          ['gitops', 'pull', 'push', 'argo', 'flux', 'drift', 'audit', 'reconcile'],
          'Did the pipeline push to the cluster or did the cluster pull?',
          3,
        ],
        [
          'Tool choice',
          ['jenkins', 'github actions', 'gitlab', 'circleci', 'argo', 'tekton', 'migrat', 'plugin'],
          'Why this tool?',
          1,
        ],
      ],
    },
    incidents: {
      prompt:
        'Describe an incident tied to delivery: a bad release reaching production, a leaked secret in a build, or the pipeline being down when you needed to ship a fix. How did it play out?',
      concepts: [
        [
          'Detection',
          [
            'alert',
            'monitor',
            'error rate',
            'customers',
            'smoke test',
            'canary',
            'noticed',
            'paged',
          ],
          'How did you find out?',
          2,
        ],
        [
          'Mitigation and rollback',
          [
            'rollback',
            'revert',
            'redeploy previous',
            'feature flag off',
            'hotfix',
            'manual deploy',
            'break glass',
            'pause',
          ],
          'How fast could you undo it?',
          3,
        ],
        [
          'Cause',
          [
            'root cause',
            'missed test',
            'config',
            'migration',
            'dependency',
            'secret',
            'process gap',
            'review',
          ],
          'Why did the pipeline let it through?',
          2,
        ],
        [
          'Communication',
          ['stakeholder', 'status', 'incident commander', 'update', 'release freeze', 'announce'],
          'Who needed to know?',
          1,
        ],
        [
          'Prevention',
          [
            'canary',
            'progressive',
            'automated rollback',
            'test added',
            'gate',
            'postmortem',
            'rotate',
            'runbook',
            'guardrail',
          ],
          'What changed in the pipeline afterwards?',
          3,
        ],
      ],
    },
  },
}
