import type { TechnologyPack } from './types'

export const KUBERNETES_PACK: TechnologyPack = {
  id: 'kubernetes',
  label: 'Kubernetes',
  serves: ['kubernetes', 'service-mesh'],
  categories: {
    architecture: {
      prompt:
        'Describe the Kubernetes architecture you ran: control plane versus nodes, how workloads were laid out across namespaces or clusters, how it scaled, and why.',
      concepts: [
        [
          'Control plane and node pools',
          [
            'control plane',
            'api server',
            'etcd',
            'scheduler',
            'kubelet',
            'node pool',
            'worker node',
            'managed',
          ],
          'Which parts were yours to run, and which were provided?',
          2,
        ],
        [
          'Workload types and scaling',
          [
            'deployment',
            'statefulset',
            'daemonset',
            'replica',
            'hpa',
            'autoscal',
            'cluster autoscaler',
            'keda',
          ],
          'How did the number of pods change with load?',
          3,
        ],
        [
          'Cluster and tenancy boundaries',
          [
            'namespace',
            'multi-cluster',
            'per environment',
            'tenant',
            'resource quota',
            'limit range',
            'isolation',
          ],
          'How did you separate teams or environments?',
          2,
        ],
        [
          'Delivery of manifests',
          [
            'helm',
            'kustomize',
            'gitops',
            'argo',
            'flux',
            'manifest',
            'rolling update',
            'deployment strategy',
          ],
          'How did a change reach the cluster?',
          2,
        ],
        [
          'Resilience across zones and nodes',
          [
            'availability zone',
            'multi-az',
            'anti-affinity',
            'pod disruption',
            'readiness',
            'liveness',
            'node failure',
            'topology spread',
          ],
          'What happened when a node or zone disappeared?',
          3,
        ],
      ],
    },
    networking: {
      prompt:
        'Trace a request from a user into a pod on that cluster, then a pod-to-pod call across namespaces. Name the components involved at each hop.',
      concepts: [
        [
          'Ingress or gateway entry point',
          [
            'ingress',
            'ingress controller',
            'gateway api',
            'load balancer',
            'nginx',
            'alb',
            'traefik',
          ],
          'How did traffic first reach the cluster?',
          3,
        ],
        [
          'Services and kube-proxy',
          [
            'service',
            'clusterip',
            'nodeport',
            'kube-proxy',
            'endpoints',
            'iptables',
            'ipvs',
            'endpointslice',
          ],
          'How did a stable address map to changing pods?',
          3,
        ],
        [
          'Pod networking (CNI)',
          ['cni', 'calico', 'cilium', 'flannel', 'vpc cni', 'overlay', 'pod cidr', 'weave'],
          'How does a pod get an address and reach another node?',
          2,
        ],
        [
          'Cluster DNS',
          ['coredns', 'cluster dns', 'service discovery', 'svc.cluster.local', 'ndots', 'dns'],
          'How does one service find another by name?',
          2,
        ],
        [
          'Network policy and segmentation',
          [
            'network policy',
            'default deny',
            'segmentation',
            'namespace isolation',
            'egress',
            'mesh',
            'mtls',
          ],
          'What restricts which pods can talk?',
          2,
        ],
      ],
    },
    security: {
      prompt:
        'What were the main security risks on that Kubernetes platform, and what specifically did you put in place for access, workloads, secrets and images?',
      concepts: [
        [
          'RBAC and service accounts',
          [
            'rbac',
            'role binding',
            'rolebinding',
            'service account',
            'least privilege',
            'clusterrole',
            'irsa',
            'workload identity',
          ],
          'Who could do what in the cluster, and how narrow was it?',
          3,
        ],
        [
          'Pod and admission security',
          [
            'pod security',
            'security context',
            'non-root',
            'privileged',
            'read-only root',
            'admission',
            'opa',
            'kyverno',
            'gatekeeper',
          ],
          'What stopped an unsafe pod from being scheduled?',
          3,
        ],
        [
          'Secrets management',
          [
            'secret',
            'sealed secrets',
            'external secrets',
            'vault',
            'kms',
            'encryption at rest',
            'csi driver',
          ],
          'Where did secrets live and how did pods get them?',
          2,
        ],
        [
          'Image supply chain',
          [
            'image scan',
            'trivy',
            'signed',
            'cosign',
            'registry',
            'sbom',
            'base image',
            'admission',
          ],
          'How did you trust what ran in the cluster?',
          2,
        ],
        [
          'API server exposure and audit',
          [
            'private endpoint',
            'api server access',
            'audit log',
            'authorized networks',
            'bastion',
            'oidc',
          ],
          'Who could reach the control plane, and from where?',
          2,
        ],
      ],
    },
    observability: {
      prompt:
        'How did you monitor that Kubernetes platform and the workloads on it? Which signals, which alerts, and what actually paged someone.',
      concepts: [
        [
          'Cluster and workload metrics',
          [
            'prometheus',
            'kube-state-metrics',
            'metrics-server',
            'cadvisor',
            'node exporter',
            'metrics',
          ],
          'Which metrics told you a workload was unhealthy?',
          3,
        ],
        [
          'Log collection',
          ['fluent', 'loki', 'elk', 'stdout', 'log aggregation', 'daemonset', 'fluentd', 'vector'],
          'How did you read logs from pods that no longer existed?',
          2,
        ],
        [
          'Alerts on symptoms and saturation',
          [
            'alert',
            'slo',
            'burn rate',
            'pagerduty',
            'alertmanager',
            'crashloop',
            'oomkilled',
            'pending',
          ],
          'Which alerts were worth waking someone for?',
          3,
        ],
        [
          'Tracing and request flow',
          ['opentelemetry', 'tracing', 'jaeger', 'span', 'tempo', 'service map'],
          'How did you follow a request across services?',
          1,
        ],
        [
          'Resource requests, limits and throttling',
          [
            'requests and limits',
            'cpu throttling',
            'saturation',
            'right-sizing',
            'vpa',
            'headroom',
            'resource request',
          ],
          'How did you know pods were sized correctly?',
          2,
        ],
      ],
    },
    troubleshooting: {
      prompt:
        'A deployment on your cluster rolled out but its pods are not serving traffic. Walk me through how you diagnose it, from the first command onwards.',
      concepts: [
        [
          'Scope and recent change',
          [
            'kubectl get',
            'rollout status',
            'which pods',
            'namespace',
            'recent change',
            'last deploy',
            'rollout history',
          ],
          'What do you check before digging into any one pod?',
          3,
        ],
        [
          'Events, logs and pod states',
          [
            'kubectl describe',
            'kubectl logs',
            'events',
            'previous',
            'crashloopbackoff',
            'imagepullbackoff',
            'oomkilled',
            'exit code',
          ],
          'How do you read why a pod is not ready?',
          3,
        ],
        [
          'Probes and configuration',
          [
            'readiness probe',
            'liveness probe',
            'configmap',
            'secret',
            'env var',
            'startup probe',
            'misconfig',
          ],
          'What could make a healthy container look unhealthy?',
          2,
        ],
        [
          'Scheduling and resources',
          [
            'pending',
            'insufficient',
            'taint',
            'toleration',
            'resource request',
            'quota',
            'node pressure',
            'unschedulable',
          ],
          'Why might a pod never start at all?',
          2,
        ],
        [
          'Service and network path',
          [
            'endpoints',
            'selector',
            'port-forward',
            'dns',
            'network policy',
            'curl',
            'service port',
            'targetport',
          ],
          'The pod is fine but traffic still fails. Where next?',
          3,
        ],
      ],
    },
    'trade-offs': {
      prompt:
        'What trade-offs did you make around Kubernetes: managed versus self-run, one cluster or many, Helm or Kustomize, stateful workloads inside or outside, or not using it at all?',
      concepts: [
        [
          'Managed versus self-managed control plane',
          ['managed', 'eks', 'gke', 'aks', 'self-managed', 'upgrade burden', 'control plane'],
          'Who ran the control plane, and why?',
          2,
        ],
        [
          'Cluster count and blast radius',
          [
            'multi-cluster',
            'single cluster',
            'blast radius',
            'per environment',
            'per team',
            'noisy neighbour',
            'noisy neighbor',
          ],
          'How many clusters, and what drove that?',
          3,
        ],
        [
          'Packaging and templating choice',
          ['helm', 'kustomize', 'jsonnet', 'raw manifests', 'operator', 'templating'],
          'How were manifests produced and why that way?',
          2,
        ],
        [
          'Stateful workloads',
          [
            'stateful',
            'managed database',
            'rds',
            'persistent volume',
            'operator',
            'csi',
            'storage class',
          ],
          'Where did the data live?',
          2,
        ],
        [
          'Complexity versus simpler platforms',
          [
            'ecs',
            'nomad',
            'serverless',
            'virtual machine',
            'too complex',
            'overkill',
            'cost of operating',
            'platform team',
          ],
          'Was Kubernetes the simplest thing that worked?',
          3,
        ],
      ],
    },
    incidents: {
      prompt:
        'Describe a production incident involving Kubernetes: a bad release, a node or zone failure, or a control plane problem. How was it detected, mitigated, communicated and prevented?',
      concepts: [
        [
          'Detection and customer impact',
          ['alert', 'error rate', 'health check', 'customers', 'symptom', 'paged', 'synthetic'],
          'What told you something was wrong?',
          2,
        ],
        [
          'Kubernetes-level mitigation',
          [
            'rollback',
            'rollout undo',
            'scale',
            'cordon',
            'drain',
            'traffic shift',
            'restart',
            'evict',
          ],
          'What did you do to the cluster to stop the damage?',
          3,
        ],
        [
          'Cause and contributing factors',
          [
            'root cause',
            'resource limit',
            'config',
            'certificate expir',
            'etcd',
            'node',
            'quota',
            'dns',
            'autoscal',
          ],
          'What had gone wrong underneath?',
          2,
        ],
        [
          'Communication',
          ['stakeholder', 'status page', 'incident commander', 'war room', 'update', 'escalat'],
          'Who was told what, and when?',
          2,
        ],
        [
          'Prevention',
          [
            'postmortem',
            'canary',
            'pod disruption budget',
            'load test',
            'guardrail',
            'admission',
            'progressive',
            'runbook',
          ],
          'What changed so it could not happen again?',
          3,
        ],
      ],
    },
  },
}
