import type { TechnologyPack } from './types'

export const OBSERVABILITY_PACK: TechnologyPack = {
  id: 'observability',
  label: 'Observability',
  serves: ['observability', 'prometheus', 'grafana'],
  categories: {
    architecture: {
      prompt:
        'Describe the monitoring and observability architecture you built: how telemetry was collected, stored, queried and kept highly available, and why it was shaped that way.',
      concepts: [
        [
          'Collection and discovery',
          [
            'scrape',
            'exporter',
            'agent',
            'service discovery',
            'otel collector',
            'opentelemetry',
            'sidecar',
            'instrument',
          ],
          'How did data get from workloads into the system?',
          3,
        ],
        [
          'Storage and retention',
          [
            'retention',
            'long-term',
            'thanos',
            'cortex',
            'mimir',
            'remote write',
            'downsampl',
            'tsdb',
            'storage',
          ],
          'How long was data kept and where?',
          3,
        ],
        [
          'Scale and cardinality',
          [
            'cardinality',
            'shard',
            'federation',
            'scale',
            'label',
            'series',
            'ingest rate',
            'memory',
          ],
          'What limited how much it could hold?',
          2,
        ],
        [
          'Availability of the monitoring itself',
          [
            'highly available',
            'ha pair',
            'redundan',
            'dead man',
            'meta-monitoring',
            'watchdog',
            'separate cluster',
          ],
          'What watched the watchers?',
          2,
        ],
        [
          'Dashboards and access',
          ['grafana', 'dashboard', 'folder', 'template', 'as code', 'provision', 'self-service'],
          'How did teams get their own views?',
          1,
        ],
      ],
    },
    networking: {
      prompt:
        'How did telemetry travel across the network in your setup: scrape paths, agents and collectors, crossing networks or regions, and what you checked when a target went silent?',
      concepts: [
        [
          'Scrape and push paths',
          [
            'scrape',
            'pull',
            'push',
            'pushgateway',
            'remote write',
            'agent',
            'collector',
            'endpoint',
          ],
          'Did the system reach out to targets or did they send data in?',
          3,
        ],
        [
          'Reachability across networks',
          ['firewall', 'vpc', 'private', 'peering', 'proxy', 'cross-region', 'allowlist', 'port'],
          'How did metrics cross a network boundary?',
          2,
        ],
        [
          'Service discovery',
          [
            'service discovery',
            'kubernetes sd',
            'consul',
            'relabel',
            'dns sd',
            'ec2 sd',
            'file sd',
          ],
          'How did new targets get picked up?',
          2,
        ],
        [
          'Debugging a missing target',
          ['targets page', 'up metric', 'curl', 'timeout', 'dns', 'tls', 'scrape error', 'status'],
          'A target stops reporting. What do you check?',
          3,
        ],
      ],
    },
    security: {
      prompt:
        'What security and privacy concerns come with observability data, and how did you handle access, sensitive content, encryption and multi-tenancy?',
      concepts: [
        [
          'Access control to telemetry',
          [
            'rbac',
            'sso',
            'authentication',
            'authoriz',
            'read-only',
            'viewer',
            'team access',
            'oauth',
          ],
          'Who could see what?',
          3,
        ],
        [
          'Sensitive data in logs and labels',
          [
            'pii',
            'sensitive',
            'redact',
            'scrub',
            'mask',
            'gdpr',
            'tokens in logs',
            'sanitis',
            'sanitiz',
          ],
          'How did you stop secrets and personal data landing in logs?',
          3,
        ],
        [
          'Transport security',
          [
            'tls',
            'mtls',
            'encrypted',
            'certificate',
            'basic auth',
            'token',
            'authenticated scrape',
          ],
          'Was telemetry encrypted in transit?',
          2,
        ],
        [
          'Tenancy and retention policy',
          ['multi-tenant', 'tenant', 'retention', 'audit', 'compliance', 'isolation', 'delete'],
          'How was data separated and expired?',
          2,
        ],
      ],
    },
    observability: {
      prompt:
        'How did you decide what to measure and alert on? Explain your approach to service-level indicators, objectives, alert design and avoiding noise.',
      concepts: [
        [
          'Golden signals, RED and USE',
          [
            'golden signal',
            'red method',
            'use method',
            'latency',
            'traffic',
            'errors',
            'saturation',
            'rate',
          ],
          'What did you measure for any service by default?',
          3,
        ],
        [
          'SLOs and error budgets',
          [
            'slo',
            'sli',
            'error budget',
            'burn rate',
            'objective',
            'availability target',
            'multi-window',
          ],
          'How did you define good enough?',
          3,
        ],
        [
          'Alerting on symptoms with runbooks',
          [
            'symptom',
            'actionable',
            'runbook',
            'page',
            'ticket',
            'severity',
            'for duration',
            'alert fatigue',
          ],
          'What made an alert worth a page?',
          3,
        ],
        [
          'Reducing noise',
          [
            'noise',
            'flapping',
            'dedupe',
            'grouping',
            'inhibit',
            'silence',
            'tuning',
            'threshold review',
          ],
          'How did you keep alerts trustworthy?',
          2,
        ],
        [
          'Correlating metrics, logs and traces',
          ['correlation', 'trace id', 'exemplar', 'drill down', 'logs and metrics', 'context'],
          'How did you move from a spike to a cause?',
          2,
        ],
      ],
    },
    troubleshooting: {
      prompt:
        'Your alerts are firing constantly, or an outage happened with no alert at all, or dashboards show gaps. Walk me through how you diagnose the monitoring itself.',
      concepts: [
        [
          'Missing data and gaps',
          [
            'gap',
            'scrape failure',
            'up metric',
            'target down',
            'staleness',
            'retention',
            'dropped',
            'ingest',
          ],
          'What causes holes in a graph?',
          3,
        ],
        [
          'High cardinality and slow queries',
          [
            'cardinality',
            'slow query',
            'label explosion',
            'recording rule',
            'timeout',
            'memory',
            'series count',
          ],
          'Why would queries or the server become slow?',
          2,
        ],
        [
          'Noisy or silent alerts',
          [
            'threshold',
            'for clause',
            'flapping',
            'false positive',
            'false negative',
            'coverage',
            'test alert',
            'blackbox',
          ],
          'Why did the alert fire, or fail to?',
          3,
        ],
        [
          'Verifying the pipeline end to end',
          ['synthetic', 'end to end', 'test metric', 'watchdog', 'dead man', 'probe', 'blackbox'],
          'How do you prove alerts would reach a human?',
          2,
        ],
        [
          'Systematic method',
          ['hypothesis', 'isolate', 'compare', 'narrow', 'recent change', 'logs', 'config diff'],
          'How did you narrow it down methodically?',
          2,
        ],
      ],
    },
    'trade-offs': {
      prompt:
        'What trade-offs did you make in observability: self-hosted versus SaaS, pull versus push, cardinality versus detail, retention versus cost, sampling traces, build versus buy?',
      concepts: [
        [
          'Self-hosted versus SaaS',
          [
            'saas',
            'datadog',
            'self-hosted',
            'open source',
            'cost',
            'operational',
            'vendor',
            'lock-in',
          ],
          'Who ran the monitoring and why?',
          3,
        ],
        [
          'Cardinality, detail and cost',
          ['cardinality', 'cost', 'label', 'aggregat', 'detail', 'sampling', 'drop', 'budget'],
          'What detail did you deliberately not keep?',
          3,
        ],
        [
          'Retention versus storage',
          ['retention', 'downsampl', 'long-term', 'cold', 'storage cost', 'compaction', 'archive'],
          'How long is long enough?',
          2,
        ],
        [
          'Sampling and tracing overhead',
          [
            'sampling',
            'head-based',
            'tail-based',
            'overhead',
            'instrument',
            'performance',
            'trace volume',
          ],
          'How much tracing could you afford?',
          2,
        ],
        [
          'Standardising versus team choice',
          [
            'standard',
            'opentelemetry',
            'consistent',
            'autonomy',
            'platform',
            'conventions',
            'naming',
          ],
          'Did every team use the same tooling?',
          1,
        ],
      ],
    },
    incidents: {
      prompt:
        'Describe an incident where observability mattered: an alert that came too late, a missed outage, an alert storm, or the monitoring system itself failing. What happened and what changed?',
      concepts: [
        [
          'Detection quality',
          [
            'detected',
            'alert',
            'late',
            'customer reported',
            'missed',
            'time to detect',
            'mttd',
            'symptom',
          ],
          'Who noticed first, you or users?',
          3,
        ],
        [
          'Triage with telemetry',
          [
            'dashboard',
            'trace',
            'logs',
            'correlate',
            'narrowed',
            'recent deploy',
            'query',
            'metric',
          ],
          'What did the data show during the incident?',
          2,
        ],
        [
          'Mitigation',
          [
            'mitigate',
            'rollback',
            'silence',
            'escalate',
            'restore monitoring',
            'failover',
            'manual check',
          ],
          'What did you do first?',
          2,
        ],
        [
          'Communication and on-call',
          ['on-call', 'page', 'escalat', 'incident commander', 'status', 'handoff', 'stakeholder'],
          'Who responded and how were they coordinated?',
          2,
        ],
        [
          'Follow-up improvements',
          [
            'postmortem',
            'new alert',
            'runbook',
            'slo',
            'coverage',
            'game day',
            'tuning',
            'action item',
          ],
          'What monitoring did you add or remove afterwards?',
          3,
        ],
      ],
    },
  },
}
