import type { TechnologyPack } from './types'

export const TERRAFORM_PACK: TechnologyPack = {
  id: 'terraform',
  label: 'Terraform',
  serves: ['terraform', 'ansible'],
  categories: {
    architecture: {
      prompt:
        'Describe how your infrastructure code was organised: modules, state, environments and providers, how a change flowed from code to real resources, and why it was laid out that way.',
      concepts: [
        [
          'Module structure and reuse',
          [
            'module',
            'composition',
            'reusable',
            'versioned module',
            'registry',
            'root module',
            'inputs',
          ],
          'How did you avoid copying the same code between environments?',
          3,
        ],
        [
          'State storage and locking',
          [
            'remote state',
            'backend',
            's3',
            'dynamodb',
            'state lock',
            'locking',
            'state file',
            'terraform cloud',
          ],
          'Where did state live and what stopped two people corrupting it?',
          3,
        ],
        [
          'Environment separation',
          [
            'workspace',
            'per environment',
            'directory',
            'account',
            'tfvars',
            'terragrunt',
            'staging',
            'production',
          ],
          'How were environments kept apart?',
          2,
        ],
        [
          'Change workflow',
          ['plan', 'apply', 'pull request', 'pipeline', 'review', 'atlantis', 'approval', 'ci'],
          'How did a change get applied?',
          2,
        ],
      ],
    },
    networking: {
      prompt:
        'Walk me through the network you defined as code: address ranges, subnets, routing, security rules, connectivity between networks and DNS.',
      concepts: [
        [
          'Address planning and subnets',
          ['cidr', 'subnet', 'public', 'private', 'availability zone', 'ip range', 'vpc'],
          'How did you carve up the address space?',
          3,
        ],
        [
          'Routing and egress',
          [
            'route table',
            'nat',
            'internet gateway',
            'transit gateway',
            'peering',
            'egress',
            'endpoint',
          ],
          'How did private resources reach the outside?',
          2,
        ],
        [
          'Security groups and rules',
          [
            'security group',
            'nacl',
            'ingress rule',
            'egress rule',
            'least',
            'firewall',
            'cidr block',
          ],
          'How were allowed paths expressed in code?',
          3,
        ],
        [
          'DNS and load balancing',
          ['route53', 'dns', 'load balancer', 'alb', 'record', 'private zone', 'certificate'],
          'How did names map to the infrastructure?',
          2,
        ],
      ],
    },
    security: {
      prompt:
        'What security concerns come with managing infrastructure through Terraform, and how did you address state contents, pipeline privileges, secrets and policy?',
      concepts: [
        [
          'State contains secrets',
          [
            'sensitive',
            'state encryption',
            'encrypted backend',
            'kms',
            'access to state',
            'bucket policy',
            'state file',
          ],
          'What is dangerous about the state file?',
          3,
        ],
        [
          'Least privilege for the pipeline',
          [
            'least privilege',
            'assume role',
            'oidc',
            'iam role',
            'short-lived',
            'separate role',
            'permission',
          ],
          'What could the automation do, and what should it not?',
          3,
        ],
        [
          'Policy as code and scanning',
          [
            'policy as code',
            'sentinel',
            'opa',
            'conftest',
            'checkov',
            'tfsec',
            'trivy',
            'guardrail',
          ],
          'How did you stop an unsafe change before it applied?',
          2,
        ],
        [
          'Secrets not in code',
          [
            'secrets manager',
            'vault',
            'tfvars',
            'environment variable',
            'not committed',
            'sops',
            'parameter store',
          ],
          'How did secrets reach resources?',
          2,
        ],
      ],
    },
    observability: {
      prompt:
        'How did you keep visibility over infrastructure managed by Terraform: knowing what changed, detecting drift, and tracing a problem back to a change?',
      concepts: [
        [
          'Plan review as visibility',
          ['plan output', 'plan in pr', 'diff', 'review', 'destroy', 'replace', 'speculative'],
          'What did reviewers see before approving?',
          2,
        ],
        [
          'Drift detection',
          ['drift', 'out of band', 'manual change', 'scheduled plan', 'driftctl', 'refresh'],
          'How did you find changes made outside Terraform?',
          3,
        ],
        [
          'Audit trail of changes',
          ['audit', 'cloudtrail', 'git history', 'who changed', 'apply log', 'run history', 'tag'],
          'Who changed what, and when?',
          2,
        ],
        [
          'Tagging and cost attribution',
          ['tag', 'cost', 'owner', 'label', 'allocation', 'inventory'],
          'How did you know what each resource was for?',
          1,
        ],
      ],
    },
    troubleshooting: {
      prompt:
        'A terraform plan wants to destroy and recreate a production resource that should not change. Walk me through what you check and what you do.',
      concepts: [
        [
          'Read the plan carefully',
          ['forces replacement', 'plan', 'diff', '-/+', 'attribute', 'change', 'must be replaced'],
          'What in the plan tells you why?',
          3,
        ],
        [
          'State versus reality',
          ['state', 'refresh', 'drift', 'import', 'state mv', 'state list', 'terraform show'],
          'How do you compare what Terraform thinks exists with what does?',
          3,
        ],
        [
          'Provider and version changes',
          [
            'provider version',
            'upgrade',
            'lock file',
            'deprecat',
            'default changed',
            'pin',
            '.terraform.lock',
          ],
          'Could the tooling itself have changed?',
          2,
        ],
        [
          'Safe ways to proceed',
          [
            'prevent_destroy',
            'lifecycle',
            'ignore_changes',
            'target',
            'moved block',
            'backup state',
            'import',
          ],
          'How would you avoid the destructive outcome?',
          2,
        ],
        [
          'Lock and apply failures',
          [
            'state lock',
            'force-unlock',
            'partial apply',
            'timeout',
            'retry',
            'dependency',
            'depends_on',
          ],
          'What if an apply fails halfway?',
          2,
        ],
      ],
    },
    'trade-offs': {
      prompt:
        'What trade-offs did you make with Terraform: workspaces or directories, monorepo or many, modules versus copy, Terraform versus Pulumi or CloudFormation, how much to automate?',
      concepts: [
        [
          'Environment strategy',
          [
            'workspace',
            'directory',
            'terragrunt',
            'account per',
            'duplicate',
            'dry',
            'drift between environments',
          ],
          'How did you balance reuse against isolation?',
          3,
        ],
        [
          'Module granularity and versioning',
          ['module', 'version', 'pin', 'too generic', 'breaking change', 'wrapper', 'registry'],
          'How big should a module be?',
          2,
        ],
        [
          'Tool choice',
          ['pulumi', 'cloudformation', 'cdk', 'opentofu', 'ansible', 'bicep', 'licen'],
          'Why Terraform rather than something else?',
          2,
        ],
        [
          'State and blast radius',
          [
            'blast radius',
            'state split',
            'small state',
            'monolithic',
            'dependency',
            'speed',
            'remote state data',
          ],
          'How did you decide what shares a state file?',
          3,
        ],
        [
          'Automation versus control',
          ['auto-apply', 'manual approval', 'review', 'speed', 'safety', 'break glass'],
          'How much was applied without a human?',
          1,
        ],
      ],
    },
    incidents: {
      prompt:
        'Describe an incident caused by or involving infrastructure code: a bad apply, state corruption, a stuck lock, or a destroyed resource. How was it found, recovered, communicated and prevented?',
      concepts: [
        [
          'Detection',
          ['alert', 'monitor', 'noticed', 'outage', 'customers', 'failed apply', 'paged'],
          'How did you find out something had gone wrong?',
          2,
        ],
        [
          'Recovery',
          [
            'restore',
            'state backup',
            'versioned bucket',
            'import',
            'rollback',
            'revert',
            'recreate',
            'snapshot',
          ],
          'How did you get the resource and the state consistent again?',
          3,
        ],
        [
          'Cause',
          [
            'root cause',
            'replace',
            'forced',
            'manual change',
            'concurrent',
            'provider',
            'typo',
            'wrong workspace',
          ],
          'What actually caused it?',
          2,
        ],
        [
          'Communication',
          ['stakeholder', 'status', 'incident commander', 'update', 'escalat', 'freeze'],
          'Who was told, and was there a change freeze?',
          1,
        ],
        [
          'Prevention',
          [
            'prevent_destroy',
            'policy',
            'approval',
            'plan review',
            'state versioning',
            'locking',
            'postmortem',
            'guardrail',
            'least privilege',
          ],
          'What now stops that change from happening?',
          3,
        ],
      ],
    },
  },
}
