import type { CommandSpec } from '@opsforge/types'

const API_PODS = [
  'payment-api-6f7c9d5b8-4kq2m',
  'payment-api-6f7c9d5b8-9tz7x',
  'payment-api-6f7c9d5b8-bh6wd',
  'payment-api-6f7c9d5b8-c2n8r',
  'payment-api-6f7c9d5b8-f5l4j',
  'payment-api-6f7c9d5b8-hx9pv',
  'payment-api-6f7c9d5b8-m7s3k',
  'payment-api-6f7c9d5b8-q4d6t',
  'payment-api-6f7c9d5b8-z8v2g',
]

function podTable(age: string): string {
  const header = 'NAME                                      READY   STATUS    RESTARTS   AGE'
  const api = API_PODS.map((name) => `${name.padEnd(42)}1/1     Running   0          ${age}`)
  const consumers = [
    'payment-events-consumer-5d8f6c7b9-2jwq8',
    'payment-events-consumer-5d8f6c7b9-r6n4c',
    'payment-events-consumer-5d8f6c7b9-vk3xz',
  ].map((name) => `${name.padEnd(42)}1/1     Running   0          3d`)
  return [header, ...api, ...consumers].join('\n')
}

export const commands: CommandSpec[] = [
  /* ---- read-only: Kubernetes --------------------------------------------- */
  {
    id: 'cmd-pods',
    command: 'kubectl get pods -n payments',
    aliases: [
      'kubectl get pods --namespace payments',
      'kubectl get po -n payments',
      'kubectl get pods -n payments -o wide',
    ],
    category: 'kubernetes',
    description: 'List the pods in the payments namespace.',
    starter: true,
    output: podTable('8m'),
    outputResolved: podTable('4m'),
  },
  {
    id: 'cmd-top',
    command: 'kubectl top pods -n payments',
    aliases: ['kubectl top pod -n payments'],
    category: 'kubernetes',
    description: 'CPU and memory use per pod.',
    starter: true,
    output: [
      'NAME                                      CPU(cores)   MEMORY(bytes)',
      ...API_PODS.map((name) => `${name.padEnd(42)}380m         612Mi`),
      'payment-events-consumer-5d8f6c7b9-2jwq8   95m          410Mi',
      'payment-events-consumer-5d8f6c7b9-r6n4c   101m         402Mi',
      'payment-events-consumer-5d8f6c7b9-vk3xz   97m          415Mi',
    ].join('\n'),
  },
  {
    id: 'cmd-nodes',
    command: 'kubectl get nodes',
    aliases: ['kubectl get no', 'kubectl get nodes -o wide'],
    category: 'kubernetes',
    description: 'List cluster nodes and their status.',
    starter: true,
    output: [
      'NAME             STATUS   ROLES    AGE    VERSION',
      'ip-10-0-1-14     Ready    <none>   41d    v1.29.4',
      'ip-10-0-1-22     Ready    <none>   41d    v1.29.4',
      'ip-10-0-1-31     Ready    <none>   41d    v1.29.4',
      'ip-10-0-1-47     Ready    <none>   19d    v1.29.4',
      'ip-10-0-2-09     Ready    <none>   41d    v1.29.4',
      'ip-10-0-2-18     Ready    <none>   41d    v1.29.4',
      'ip-10-0-2-26     Ready    <none>   41d    v1.29.4',
      'ip-10-0-2-33     Ready    <none>   12d    v1.29.4',
      'ip-10-0-3-05     Ready    <none>   41d    v1.29.4',
      'ip-10-0-3-12     Ready    <none>   41d    v1.29.4',
      'ip-10-0-3-29     Ready    <none>   9d     v1.29.4',
      'ip-10-0-3-52     Ready    <none>   10m    v1.29.4',
    ].join('\n'),
  },
  {
    id: 'cmd-events',
    command: 'kubectl get events -n payments --sort-by=.lastTimestamp',
    aliases: ['kubectl get events -n payments', 'kubectl get events --namespace payments'],
    category: 'kubernetes',
    description: 'Recent events in the payments namespace, oldest first.',
    starter: true,
    output: [
      'LAST SEEN   TYPE     REASON               OBJECT                                MESSAGE',
      '10m         Normal   Drain                node/ip-10-0-3-17                     Autoscaler removed underused node (scale-down)',
      '10m         Normal   Scheduled            pod/payment-events-consumer-…-vk3xz    Rescheduled onto ip-10-0-3-52',
      '8m          Normal   ScalingReplicaSet    deployment/payment-api                Scaled up replica set payment-api-6f7c9d5b8 to 3',
      '8m          Normal   ScalingReplicaSet    deployment/payment-api                Scaled down replica set payment-api-5c4b7d6f9 to 6',
      '7m          Normal   ScalingReplicaSet    deployment/payment-api                Scaled up replica set payment-api-6f7c9d5b8 to 9',
      '7m          Normal   ScalingReplicaSet    deployment/payment-api                Scaled down replica set payment-api-5c4b7d6f9 to 0',
    ].join('\n'),
  },
  {
    id: 'cmd-logs',
    command: 'kubectl logs deploy/payment-api -n payments --tail=20',
    aliases: [
      'kubectl logs deployment/payment-api -n payments --tail=20',
      'kubectl logs deploy/payment-api -n payments',
      'kubectl logs -l app=payment-api -n payments --tail=20',
    ],
    category: 'kubernetes',
    description: 'Tail the application logs of the payment-api deployment.',
    output: [
      '14:08:41 WARN  upstream timeout after 8000ms route=POST /v1/payments method=card',
      '14:08:41 ERROR 504 returned to checkout-web request_id=a1c9e2',
      '14:08:42 INFO  payment authorized method=wallet latency=191ms',
      '14:08:43 WARN  upstream timeout after 8000ms route=POST /v1/payments method=card',
      '14:08:43 ERROR 504 returned to checkout-web request_id=b7d410',
      '14:08:44 WARN  upstream timeout after 8000ms route=POST /v1/payments method=card',
      '14:08:46 INFO  payment authorized method=wallet latency=204ms',
      '14:08:46 WARN  upstream timeout after 8000ms route=POST /v1/payments method=card',
      '(showing the 8 most recent lines; use the Logs panel to search)',
    ].join('\n'),
  },
  {
    id: 'cmd-describe',
    command: 'kubectl describe deployment payment-api -n payments',
    aliases: [
      'kubectl describe deploy payment-api -n payments',
      'kubectl describe deploy/payment-api -n payments',
    ],
    category: 'kubernetes',
    description: 'Show the deployment spec, environment and rollout strategy.',
    output: [
      'Name:                   payment-api',
      'Namespace:              payments',
      'Replicas:               9 desired | 9 updated | 9 total | 9 available',
      'StrategyType:           RollingUpdate',
      'Pod Template:',
      '  Image:        registry.internal/payment-api:v2.14.0',
      '  Limits:       cpu: 2, memory: 1Gi',
      '  Requests:     cpu: 500m, memory: 512Mi',
      '  Environment:',
      '    DB_HOST:             postgres-payments',
      '    DB_POOL_MAX:         20',
      '    DB_POOL_ACQUIRE_MS:  8000',
      '    DB_TX_TIMEOUT_MS:    <unset>',
      '    PREAUTH_ENABLED:     true',
      'Capacity check (from annotations):',
      '  9 replicas x DB_POOL_MAX 20 = 180 connections (payment-api)',
      '  3 consumers x 8            =  24 connections (payment-events-consumer)',
    ].join('\n'),
  },
  {
    id: 'cmd-rollout-history',
    command: 'kubectl rollout history deployment/payment-api -n payments',
    aliases: [
      'kubectl rollout history deploy/payment-api -n payments',
      'kubectl rollout history deployment payment-api -n payments',
    ],
    category: 'deploy',
    description: 'List the revisions of the payment-api deployment.',
    output: [
      'deployment.apps/payment-api',
      'REVISION  CHANGE-CAUSE',
      '12        v2.13.1: retry policy for PSP 429s',
      '13        v2.13.2: fix currency rounding on refunds',
      '14        v2.14.0: pre-authorization hold (PAY-2291)   <- 8 minutes ago',
    ].join('\n'),
  },
  {
    id: 'cmd-argocd-history',
    command: 'argocd app history payment-api',
    aliases: ['argocd app history payment-api -o wide'],
    category: 'deploy',
    description: 'Deploy history for the payment-api application.',
    output: [
      'ID  DATE                 REVISION',
      '41  2026-10-07 09:12:44  v2.13.1',
      '42  2026-10-08 16:03:10  v2.13.2',
      '43  2026-10-09 14:00:21  v2.14.0 (PAY-2291 pre-authorization hold)',
    ].join('\n'),
  },
  {
    id: 'cmd-rollout-diff',
    command: 'kubectl rollout history deployment/payment-api -n payments --revision=14',
    aliases: [
      'kubectl rollout history deploy/payment-api -n payments --revision=14',
      'kubectl rollout history deployment/payment-api -n payments --revision 14',
    ],
    category: 'deploy',
    description: 'Show what revision 14 changed.',
    unlockedBy: ['e-cmd-rollout-history'],
    output: [
      'deployment.apps/payment-api with revision #14',
      'Pod Template:',
      '  Image:   registry.internal/payment-api:v2.14.0   (was v2.13.2)',
      '  Environment (changed):',
      '    PREAUTH_ENABLED: true                            (new)',
      'Change description (PAY-2291):',
      '  "Place a hold on the card before capture. The hold opens a DB transaction and writes an audit',
      '   record through the shared pool before the PSP authorize call is made."',
    ].join('\n'),
  },

  /* ---- read-only: dependencies ------------------------------------------- */
  {
    id: 'cmd-redis-info',
    command: 'redis-cli -h redis-sessions info stats',
    aliases: ['redis-cli info stats', 'redis-cli -h redis-sessions info'],
    category: 'cache',
    description: 'Redis counters: hit ratio, evictions, clients.',
    output: [
      '# Stats',
      'total_commands_processed:84211930',
      'instantaneous_ops_per_sec:2140',
      'keyspace_hits:81970412',
      'keyspace_misses:2241518',
      'keyspace_hit_ratio:0.974',
      'evicted_keys:0',
      'rejected_connections:0',
      'connected_clients:212',
      'blocked_clients:0',
    ].join('\n'),
  },
  {
    id: 'cmd-kafka-group',
    command:
      'kafka-consumer-groups --bootstrap-server kafka-payments:9092 --describe --group payment-events',
    aliases: [
      'kafka-consumer-groups.sh --bootstrap-server kafka-payments:9092 --describe --group payment-events',
      'kafka-consumer-groups --describe --group payment-events',
    ],
    category: 'messaging',
    description: 'Describe consumer group lag and member state.',
    output: [
      'GROUP           TOPIC             PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG    CONSUMER-ID',
      'payment-events  payment-captured  0          8120344         8136720         16376  consumer-2jwq8',
      'payment-events  payment-captured  1          8098712         8115021         16309  consumer-r6n4c',
      'payment-events  payment-captured  2          8101893         8118222         16329  consumer-vk3xz',
      '',
      'State: Stable   Members: 3   Rebalances (1h): 0',
      'Brokers: 3/3 in sync, under-replicated partitions: 0',
      'Avg batch commit time: 14.2s (poll 0.1s, process 14.1s: waiting on database writes)',
    ].join('\n'),
  },
  {
    id: 'cmd-psp-health',
    command: 'curl -s https://psp-gateway.internal/health',
    aliases: ['curl https://psp-gateway.internal/health', 'curl -s psp-gateway.internal/health'],
    category: 'network',
    description: 'Check the PSP gateway health endpoint.',
    output: [
      '{',
      '  "status": "ok",',
      '  "provider": "healthy",',
      '  "authorize_p99_ms": 310,',
      '  "errors_15m": 0',
      '}',
    ].join('\n'),
  },

  /* ---- read-only: database ------------------------------------------------ */
  {
    id: 'cmd-pg-activity',
    command: 'psql payments -c "select state, count(*) from pg_stat_activity group by state"',
    aliases: [
      'psql -c "select state, count(*) from pg_stat_activity group by state"',
      'psql -c "select state, count(*) from pg_stat_activity group by 1"',
      'psql payments -c "select state, count(*) from pg_stat_activity group by 1"',
      'psql payments -c "select count(*), state from pg_stat_activity group by state"',
    ],
    category: 'database',
    description: 'Count database sessions by state.',
    output: [
      '        state         | count',
      '----------------------+-------',
      ' idle in transaction  |   176',
      ' active               |    14',
      ' idle                 |     6',
      '(3 rows)',
    ].join('\n'),
    outputResolved: [
      '        state         | count',
      '----------------------+-------',
      ' active               |    11',
      ' idle                 |    71',
      '(2 rows)',
    ].join('\n'),
  },
  {
    id: 'cmd-pg-idle-detail',
    command:
      'psql payments -c "select pid, application_name, now() - xact_start as xact_age, left(query, 60) from pg_stat_activity where state = \'idle in transaction\' order by xact_age desc limit 5"',
    aliases: [
      'psql -c "select pid, application_name, now() - xact_start as xact_age, left(query, 60) from pg_stat_activity where state = \'idle in transaction\' order by xact_age desc limit 5"',
      'psql payments -c "select * from pg_stat_activity where state = \'idle in transaction\'"',
      'psql -c "select * from pg_stat_activity where state = \'idle in transaction\'"',
    ],
    category: 'database',
    description: 'Show the oldest idle-in-transaction sessions and who owns them.',
    unlockedBy: ['e-cmd-pg-activity'],
    output: [
      '  pid  | application_name |  xact_age | left',
      '-------+------------------+-----------+--------------------------------------------------------------',
      ' 18842 | payment-api      | 00:07:52  | SELECT id FROM preauth_holds WHERE order_id = $1 FOR UPDATE',
      ' 18851 | payment-api      | 00:07:49  | SELECT id FROM preauth_holds WHERE order_id = $1 FOR UPDATE',
      ' 18873 | payment-api      | 00:07:31  | SELECT id FROM preauth_holds WHERE order_id = $1 FOR UPDATE',
      ' 18902 | payment-api      | 00:07:12  | SELECT id FROM preauth_holds WHERE order_id = $1 FOR UPDATE',
      ' 18919 | payment-api      | 00:06:58  | SELECT id FROM preauth_holds WHERE order_id = $1 FOR UPDATE',
      '(5 rows)',
    ].join('\n'),
  },
  {
    id: 'cmd-pg-maxconn',
    command: 'psql payments -c "show max_connections"',
    aliases: ['psql -c "show max_connections"'],
    category: 'database',
    description: 'Show the configured connection limit.',
    output: [' max_connections', '-----------------', ' 200', '(1 row)'].join('\n'),
  },

  /* ---- mutating ---------------------------------------------------------- */
  {
    id: 'cmd-rollout-undo',
    command: 'kubectl rollout undo deployment/payment-api -n payments',
    aliases: [
      'kubectl rollout undo deploy/payment-api -n payments',
      'kubectl rollout undo deployment/payment-api --to-revision=13 -n payments',
      'kubectl rollout undo deployment payment-api -n payments',
    ],
    category: 'deploy',
    description: 'Roll payment-api back to the previous revision.',
    mutating: true,
    remediationId: 'act-rollback',
    output: 'deployment.apps/payment-api rolled back',
  },
  {
    id: 'cmd-set-flag',
    command: 'kubectl set env deployment/payment-api PREAUTH_ENABLED=false -n payments',
    aliases: [
      'kubectl set env deploy/payment-api PREAUTH_ENABLED=false -n payments',
      'kubectl set env deployment/payment-api -n payments PREAUTH_ENABLED=false',
    ],
    category: 'kubernetes',
    description: 'Turn off the pre-authorization flag.',
    mutating: true,
    remediationId: 'act-disable-flag',
    output: 'deployment.apps/payment-api env updated',
  },
  {
    id: 'cmd-restart',
    command: 'kubectl rollout restart deployment/payment-api -n payments',
    aliases: ['kubectl rollout restart deploy/payment-api -n payments'],
    category: 'kubernetes',
    description: 'Restart all payment-api pods.',
    mutating: true,
    remediationId: 'act-restart',
    output: 'deployment.apps/payment-api restarted',
  },
  {
    id: 'cmd-scale',
    command: 'kubectl scale deployment/payment-api --replicas=18 -n payments',
    aliases: [
      'kubectl scale deploy/payment-api --replicas=18 -n payments',
      'kubectl scale deployment/payment-api --replicas=12 -n payments',
      'kubectl scale deployment/payment-api --replicas=15 -n payments',
      'kubectl scale deployment/payment-api --replicas=20 -n payments',
    ],
    category: 'kubernetes',
    description: 'Scale payment-api out.',
    mutating: true,
    remediationId: 'act-scale-api',
    output: 'deployment.apps/payment-api scaled',
  },
  {
    id: 'cmd-pg-terminate',
    command:
      'psql payments -c "select pg_terminate_backend(pid) from pg_stat_activity where state = \'idle in transaction\'"',
    aliases: [
      'psql -c "select pg_terminate_backend(pid) from pg_stat_activity where state = \'idle in transaction\'"',
    ],
    category: 'database',
    description: 'Terminate every idle-in-transaction session.',
    mutating: true,
    remediationId: 'act-kill-idle',
    output: ' pg_terminate_backend\n----------------------\n t  (176 rows)',
  },
  {
    id: 'cmd-redis-flush',
    command: 'redis-cli -h redis-sessions flushall',
    aliases: ['redis-cli flushall', 'redis-cli -h redis-sessions flushdb'],
    category: 'cache',
    description: 'Delete every key in Redis.',
    mutating: true,
    remediationId: 'act-flush-redis',
    output: 'OK',
  },
]
