import type { EvidenceNode } from '@opsforge/types'

type Draft = Omit<EvidenceNode, 'requires'> & { requires?: string[] }

function node(draft: Draft): EvidenceNode {
  return { requires: [], ...draft }
}

/*
 * The scenario graph. Only `trigger: start` nodes are visible when the page arrives. Everything else
 * is discovered by looking: opening a metric, searching logs, opening a trace, running a command, or
 * observing the effect of a remediation. `requires` encodes "you cannot ask this until you know that".
 */
export const evidence: EvidenceNode[] = [
  /* ---- visible on arrival -------------------------------------------------- */
  node({
    id: 'e-baseline',
    title: 'Baseline before the incident',
    detail:
      'At T+00 traffic was normal: payment-api p99 0.31 s, error rate 0.2%, checkout success 99.6%.',
    channel: 'report',
    serviceId: 'payment-api',
    role: 'noise',
    phase: 'triage',
    at: 0,
    trigger: { kind: 'start' },
    hint: 'Given on arrival.',
  }),
  node({
    id: 'e-alert-latency',
    title: 'Alert: PaymentApiLatencyP99High firing',
    detail: 'p99 latency for payment-api above 1 s for 5 minutes. Current value 8.2 s.',
    channel: 'alert',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'triage',
    at: 11,
    trigger: { kind: 'start' },
    hint: 'Given on arrival.',
  }),
  node({
    id: 'e-alert-errors',
    title: 'Alert: PaymentApiErrorRateHigh firing',
    detail: '5xx ratio above 5% since T+10. Current value 18.4%.',
    channel: 'alert',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'triage',
    at: 12,
    trigger: { kind: 'start' },
    hint: 'Given on arrival.',
  }),
  node({
    id: 'e-alert-kafka',
    title: 'Alert: KafkaConsumerLagHigh firing',
    detail: 'Consumer group payment-events-consumer is 48k messages behind and growing.',
    channel: 'alert',
    serviceId: 'kafka-payments',
    role: 'symptom',
    phase: 'triage',
    at: 13,
    trigger: { kind: 'start' },
    bearsOn: { supports: ['h-kafka'] },
    hint: 'Given on arrival.',
  }),

  /* ---- metrics ------------------------------------------------------------ */
  node({
    id: 'e-metric-latency',
    title: 'Latency began climbing at T+06',
    detail:
      'p99 latency was flat at ~0.33 s until T+06, then rose every minute without recovering. The shape is a ramp, not periodic spikes.',
    channel: 'metrics',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'triage',
    at: 6,
    trigger: { kind: 'view', channel: 'metrics', target: 'm-latency' },
    bearsOn: { supports: ['h-deploy'] },
    hint: 'Open the payment-api p99 latency series and read the onset time.',
  }),
  node({
    id: 'e-metric-errors',
    title: 'Errors started at T+07 and are timeouts',
    detail:
      'Error rate rose from 0.3% at T+06 to 18.4% at T+14, tracking the latency ramp. The errors are 504 timeouts, not 500s from application exceptions.',
    channel: 'metrics',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'triage',
    at: 12,
    trigger: { kind: 'view', channel: 'metrics', target: 'm-errors' },
    hint: 'Open the payment-api error-rate series.',
  }),
  node({
    id: 'e-metric-checkout',
    title: 'Checkout success fell with the same ramp',
    detail:
      'Checkout success dropped from 99.6% to 81.6%. At current volume this is roughly $41k per hour of revenue at risk.',
    channel: 'metrics',
    serviceId: 'checkout-web',
    role: 'symptom',
    phase: 'triage',
    trigger: { kind: 'view', channel: 'metrics', target: 'm-checkout-success' },
    hint: 'Open the checkout success rate series to size the business impact.',
  }),
  node({
    id: 'e-metric-cpu',
    title: 'payment-api CPU is flat at ~42%',
    detail:
      'CPU has not moved across the whole window. The pods are not compute-bound; they are waiting.',
    channel: 'metrics',
    serviceId: 'payment-api',
    role: 'ruled-out',
    phase: 'isolation',
    trigger: { kind: 'view', channel: 'metrics', target: 'm-cpu' },
    bearsOn: { refutes: ['h-capacity-api'] },
    hint: 'Open the payment-api CPU series.',
  }),
  node({
    id: 'e-metric-traffic',
    title: 'Request rate is steady at ~650 req/s',
    detail:
      'There was no traffic spike or retry storm at the edge. Load is the same as before the incident.',
    channel: 'metrics',
    serviceId: 'payment-api',
    role: 'ruled-out',
    phase: 'isolation',
    trigger: { kind: 'view', channel: 'metrics', target: 'm-traffic' },
    bearsOn: { refutes: ['h-capacity-api'] },
    hint: 'Open the payment-api request-rate series.',
  }),
  node({
    id: 'e-metric-redis',
    title: 'Redis blipped at T+02, then recovered',
    detail:
      'Redis p99 latency spiked to 6.8 ms at T+02 during a background save and was back to 0.8 ms by T+04. It has been stable for 10 minutes, long before errors began.',
    channel: 'metrics',
    serviceId: 'redis-sessions',
    role: 'ruled-out',
    phase: 'isolation',
    at: 2,
    trigger: { kind: 'view', channel: 'metrics', target: 'm-redis-latency' },
    bearsOn: { refutes: ['h-redis'] },
    hint: 'Open the Redis latency series and compare the spike time with the error onset.',
  }),
  node({
    id: 'e-metric-kafka',
    title: 'Kafka consumer lag grows from T+08',
    detail: 'Lag started rising two minutes after the first errors and reached 48k messages.',
    channel: 'metrics',
    serviceId: 'kafka-payments',
    role: 'symptom',
    phase: 'isolation',
    at: 10,
    trigger: { kind: 'view', channel: 'metrics', target: 'm-kafka-lag' },
    bearsOn: { supports: ['h-kafka'] },
    hint: 'Open the Kafka consumer lag series and compare its onset with the API metrics.',
  }),
  node({
    id: 'e-metric-db-conn',
    title: 'Database connections climbed to 98% from T+06',
    detail:
      'Connection usage rose from 30% at T+05 to 90% at T+09 and 98% now, against max_connections of 200. The climb starts at the same minute as the latency ramp.',
    channel: 'metrics',
    serviceId: 'postgres-payments',
    role: 'mechanism',
    phase: 'diagnosis',
    at: 9,
    trigger: { kind: 'view', channel: 'metrics', target: 'm-db-connections' },
    bearsOn: { supports: ['h-db-pool', 'h-deploy'] },
    hint: 'Open the postgres-payments connection series.',
  }),
  node({
    id: 'e-metric-db-idle',
    title: '176 sessions are "idle in transaction"',
    detail:
      'Sessions idle in transaction went from 2 to 176 starting at T+06. Those sessions hold a connection and do no work; this is what fills the pool.',
    channel: 'metrics',
    serviceId: 'postgres-payments',
    role: 'mechanism',
    phase: 'diagnosis',
    at: 8,
    trigger: { kind: 'view', channel: 'metrics', target: 'm-db-idle-tx' },
    bearsOn: { supports: ['h-db-pool', 'h-deploy'] },
    hint: 'Open the postgres-payments "idle in transaction" series.',
  }),
  node({
    id: 'e-metric-db-cpu',
    title: 'Database CPU is ~31% and flat',
    detail:
      'The database is not compute- or IO-bound. It is running out of connection slots, not capacity.',
    channel: 'metrics',
    serviceId: 'postgres-payments',
    role: 'ruled-out',
    phase: 'isolation',
    trigger: { kind: 'view', channel: 'metrics', target: 'm-db-cpu' },
    bearsOn: { refutes: ['h-db-compute'] },
    hint: 'Open the postgres-payments CPU series.',
  }),

  /* ---- commands ----------------------------------------------------------- */
  node({
    id: 'e-cmd-pods',
    title: 'All payment-api pods are 8 minutes old',
    detail:
      'Nine payment-api pods are Running with zero restarts and an age of 8m. The consumers are 3 days old. The API pods were all replaced shortly before the latency ramp.',
    channel: 'command',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'triage',
    at: 6,
    trigger: { kind: 'command', commandIds: ['cmd-pods'] },
    bearsOn: { supports: ['h-deploy'], refutes: ['h-k8s-node'] },
    hint: 'List the pods in the payments namespace and read the AGE column.',
  }),
  node({
    id: 'e-cmd-top',
    title: 'Pods are using ~19% of their CPU limit',
    detail:
      'Each payment-api pod uses about 380m of a 2000m limit, memory well under limit. No throttling.',
    channel: 'command',
    serviceId: 'payment-api',
    role: 'ruled-out',
    phase: 'isolation',
    trigger: { kind: 'command', commandIds: ['cmd-top'] },
    bearsOn: { refutes: ['h-capacity-api'] },
    hint: 'kubectl top pods.',
  }),
  node({
    id: 'e-cmd-nodes',
    title: 'A node was drained at T+04; the cluster is healthy',
    detail:
      'All 12 nodes are Ready. Node ip-10-0-3-17 was drained by the autoscaler at T+04 and its pods rescheduled within a minute. Nothing has restarted since.',
    channel: 'command',
    serviceId: 'k8s-platform',
    role: 'ruled-out',
    phase: 'isolation',
    at: 4,
    trigger: { kind: 'command', commandIds: ['cmd-nodes', 'cmd-events'] },
    bearsOn: { refutes: ['h-k8s-node'] },
    hint: 'kubectl get events (or get nodes), then compare the drain time with the error onset.',
  }),
  node({
    id: 'e-cmd-redis',
    title: 'Redis is healthy: 97% hit ratio, no evictions',
    detail: 'keyspace hit ratio 97.4%, evicted_keys 0, connected_clients 212, blocked_clients 0.',
    channel: 'command',
    serviceId: 'redis-sessions',
    role: 'ruled-out',
    phase: 'isolation',
    trigger: { kind: 'command', commandIds: ['cmd-redis-info'] },
    bearsOn: { refutes: ['h-redis'] },
    hint: 'redis-cli info stats.',
  }),
  node({
    id: 'e-cmd-kafka',
    title: 'Kafka brokers are fine; the consumer is slow',
    detail:
      'Brokers show all partitions in sync and no under-replicated partitions. The consumer group is stable but each batch commit takes 14 s, waiting on database writes.',
    channel: 'command',
    serviceId: 'kafka-payments',
    role: 'symptom',
    phase: 'isolation',
    trigger: { kind: 'command', commandIds: ['cmd-kafka-group'] },
    bearsOn: { refutes: ['h-kafka'], supports: ['h-db-pool'] },
    hint: 'Describe the consumer group and read where the time is spent.',
  }),
  node({
    id: 'e-cmd-psp',
    title: 'The payment provider is healthy',
    detail: 'psp-gateway authorize p99 is 310 ms with 0 errors in the last 15 minutes.',
    channel: 'command',
    serviceId: 'psp-gateway',
    role: 'ruled-out',
    phase: 'isolation',
    trigger: { kind: 'command', commandIds: ['cmd-psp-health'] },
    bearsOn: { refutes: ['h-psp'] },
    hint: 'Check the PSP gateway health endpoint.',
  }),
  node({
    id: 'e-cmd-rollout-history',
    title: 'payment-api v2.14.0 was rolled out at T+06',
    detail:
      'Revision 14 (v2.14.0, "pre-authorization hold, PAY-2291") replaced revision 13 (v2.13.2) at T+06, eight minutes ago. It is the only change to payment-api this week, and it lines up with the start of the latency ramp.',
    channel: 'change',
    serviceId: 'payment-api',
    role: 'root-cause',
    phase: 'diagnosis',
    at: 6,
    trigger: {
      kind: 'command',
      commandIds: ['cmd-rollout-history', 'cmd-argocd-history', 'cmd-events'],
    },
    bearsOn: { supports: ['h-deploy'] },
    hint: 'Check recent changes with kubectl rollout history (or the GitOps history).',
  }),
  node({
    id: 'e-cmd-rollout-diff',
    title: 'v2.14.0 enabled pre-authorization behind a flag',
    detail:
      'Revision 14 adds ConfigMap flag PREAUTH_ENABLED=true. The change description says the hold opens a DB transaction and writes an audit record through the shared pool inside that transaction.',
    channel: 'change',
    serviceId: 'payment-api',
    role: 'root-cause',
    phase: 'diagnosis',
    at: 6,
    requires: ['e-cmd-rollout-history'],
    trigger: { kind: 'command', commandIds: ['cmd-rollout-diff'] },
    bearsOn: { supports: ['h-deploy', 'h-db-pool'] },
    hint: 'Inspect revision 14 once you know which revision changed.',
  }),
  node({
    id: 'e-cmd-describe',
    title: 'Pool is 20 per pod with no headroom',
    detail:
      '9 replicas × DB_POOL_MAX=20 = 180 connections, plus 3 consumers × 8 = 24. The total is 204 against max_connections of 200: there is no connection headroom, and no transaction timeout is configured.',
    channel: 'command',
    serviceId: 'payment-api',
    role: 'contributing',
    phase: 'diagnosis',
    trigger: { kind: 'command', commandIds: ['cmd-describe'] },
    bearsOn: { supports: ['h-pool-config'] },
    hint: 'kubectl describe the deployment and add up the pool sizes.',
  }),
  node({
    id: 'e-cmd-pg-activity',
    title: 'Sessions by state: 176 idle in transaction',
    detail:
      'pg_stat_activity shows 176 sessions idle in transaction, 14 active, 6 idle. Writes are rolled back when a request fails, so there is no data corruption.',
    channel: 'command',
    serviceId: 'postgres-payments',
    role: 'mechanism',
    phase: 'diagnosis',
    trigger: { kind: 'command', commandIds: ['cmd-pg-activity'] },
    bearsOn: { supports: ['h-db-pool'], refutes: ['h-db-compute'] },
    hint: 'Group pg_stat_activity by state.',
  }),
  node({
    id: 'e-cmd-pg-idle-detail',
    title: 'Idle transactions are payment-api preauth holds',
    detail:
      'The oldest idle-in-transaction sessions belong to payment-api, each open for 6–8 minutes, last statement "SELECT … FROM preauth_holds … FOR UPDATE". The transactions began, then stalled before commit.',
    channel: 'command',
    serviceId: 'postgres-payments',
    role: 'root-cause',
    phase: 'diagnosis',
    requires: ['e-cmd-pg-activity'],
    trigger: { kind: 'command', commandIds: ['cmd-pg-idle-detail'] },
    bearsOn: { supports: ['h-db-pool', 'h-deploy'] },
    hint: 'After seeing idle-in-transaction sessions, find who owns them and what they last ran.',
  }),

  /* ---- logs --------------------------------------------------------------- */
  node({
    id: 'e-log-timeouts',
    title: 'payment-api logs: card requests time out at 8 s',
    detail:
      'Errors are "upstream timeout after 8000ms" on card payments. Wallet payments in the same window succeed in under 500 ms.',
    channel: 'logs',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'triage',
    trigger: { kind: 'view', channel: 'logs', target: 'payment-api' },
    hint: 'Open the payment-api logs.',
  }),
  node({
    id: 'e-log-pool',
    title: 'HikariPool: no connection available, 52 waiting',
    detail:
      'The connection pool is fully active (20 of 20, none idle) with up to 52 requests waiting, each timing out after the configured wait.',
    channel: 'logs',
    serviceId: 'payment-api',
    role: 'mechanism',
    phase: 'diagnosis',
    at: 8,
    trigger: {
      kind: 'search',
      serviceId: 'payment-api',
      terms: ['pool', 'hikari', 'connection', 'sqlexception'],
    },
    bearsOn: { supports: ['h-db-pool'] },
    hint: 'Search the payment-api logs for pool or connection errors.',
  }),
  node({
    id: 'e-log-preauth',
    title: 'PreAuthHoldService holds a connection while waiting for a second one',
    detail:
      'Each pre-authorization begins a transaction on one pooled connection and, while it is open, waits for a second connection for the audit write. Under load all connections are held by transactions waiting for another.',
    channel: 'logs',
    serviceId: 'payment-api',
    role: 'root-cause',
    phase: 'diagnosis',
    at: 7,
    trigger: {
      kind: 'search',
      serviceId: 'payment-api',
      terms: ['preauth', 'pre-auth', 'authoriz', 'audit', 'hold', 'tx open', 'transaction'],
    },
    bearsOn: { supports: ['h-deploy', 'h-db-pool'] },
    hint: 'Search for the new code path (pre-authorization, audit, hold or transaction).',
  }),
  node({
    id: 'e-log-pg-slots',
    title: 'Postgres: remaining connection slots are reserved',
    detail:
      'The database is rejecting new clients ("too many clients already") because connections are exhausted, not because queries are slow.',
    channel: 'logs',
    serviceId: 'postgres-payments',
    role: 'mechanism',
    phase: 'diagnosis',
    at: 10,
    trigger: {
      kind: 'search',
      serviceId: 'postgres-payments',
      terms: ['fatal', 'slots', 'too many', 'connection', 'error'],
    },
    bearsOn: { supports: ['h-db-pool'] },
    hint: 'Search the Postgres logs for FATAL or connection errors.',
  }),
  node({
    id: 'e-log-consumer',
    title: 'Consumer batches time out waiting for a database connection',
    detail:
      'payment-events-consumer cannot get a database connection and retries, so offsets are committed slowly and lag grows.',
    channel: 'logs',
    serviceId: 'payment-events-consumer',
    role: 'symptom',
    phase: 'isolation',
    trigger: { kind: 'view', channel: 'logs', target: 'payment-events-consumer' },
    bearsOn: { refutes: ['h-kafka'], supports: ['h-db-pool'] },
    hint: 'Open the payment-events-consumer logs.',
  }),

  /* ---- traces ------------------------------------------------------------- */
  node({
    id: 'e-trace-slow',
    title: 'A slow request spent 5.7 s acquiring a DB connection',
    detail:
      'Of 6.2 s total, 5.7 s was db.acquire_connection (47 requests waiting). The downstream calls (fraud-scoring 22 ms, INSERT 6 ms, Redis 1 ms) were fast.',
    channel: 'traces',
    serviceId: 'payment-api',
    role: 'mechanism',
    phase: 'diagnosis',
    trigger: { kind: 'view', channel: 'traces', target: 'tr-slow-1' },
    bearsOn: { supports: ['h-db-pool'], refutes: ['h-fraud', 'h-psp', 'h-redis'] },
    hint: 'Open a slow card-payment trace and find the longest span.',
  }),
  node({
    id: 'e-trace-preauth',
    title: 'The preauth transaction waits for a second connection while holding one',
    detail:
      'Inside db.tx(preauth_hold) the code calls db.acquire_connection again (audit_log) and waits 3.8 s with the first connection still held. Each request pins two connections.',
    channel: 'traces',
    serviceId: 'payment-api',
    role: 'root-cause',
    phase: 'diagnosis',
    trigger: { kind: 'view', channel: 'traces', target: 'tr-slow-2' },
    bearsOn: { supports: ['h-deploy', 'h-db-pool'] },
    hint: 'Open the trace that contains a db.tx span and read its children.',
  }),
  node({
    id: 'e-trace-err',
    title: 'Failed requests time out waiting for a pooled connection',
    detail:
      'The 504 trace shows 7.96 s in db.acquire_connection and an error "timeout waiting for a pooled connection".',
    channel: 'traces',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'triage',
    trigger: { kind: 'view', channel: 'traces', target: 'tr-err-1' },
    bearsOn: { supports: ['h-db-pool'] },
    hint: 'Open the failed request trace.',
  }),
  node({
    id: 'e-trace-wallet',
    title: 'Wallet payments are unaffected',
    detail:
      'A wallet payment completed in 188 ms with a 3 ms connection acquire. Only the card path is slow, so the problem is confined to one code path.',
    channel: 'traces',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'isolation',
    trigger: { kind: 'view', channel: 'traces', target: 'tr-wallet-ok' },
    bearsOn: { supports: ['h-deploy'] },
    hint: 'Open a successful trace from a different payment method.',
  }),

  /* ---- after remediation -------------------------------------------------- */
  node({
    id: 'e-fix-applied',
    title: 'Mitigation applied',
    detail:
      'A fix that removes the failing code path has been applied. Confirm that the symptoms actually recover.',
    channel: 'report',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'verification',
    trigger: { kind: 'action', actionId: 'act-rollback' },
    hint: 'Revealed when the rollback is applied.',
  }),
  node({
    id: 'e-fix-applied-flag',
    title: 'Pre-authorization disabled',
    detail: 'The flag has been turned off. Confirm that the symptoms actually recover.',
    channel: 'report',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'verification',
    trigger: { kind: 'action', actionId: 'act-disable-flag' },
    hint: 'Revealed when the flag is disabled.',
  }),
  node({
    id: 'e-verify-recovered',
    title: 'Recovery confirmed: errors 0.3%, p99 0.31 s, connections 41%',
    detail:
      'After the fix, error rate, latency and connection usage returned to baseline within five minutes.',
    channel: 'metrics',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'verification',
    trigger: { kind: 'view', channel: 'metrics', target: 'm-errors' },
    requires: ['e-fix-applied'],
    hint: 'Re-open the error-rate series after the fix.',
  }),
  node({
    id: 'e-verify-recovered-flag',
    title: 'Recovery confirmed after disabling the flag',
    detail:
      'Error rate, latency and connection usage returned to baseline within five minutes of the flag change.',
    channel: 'metrics',
    serviceId: 'payment-api',
    role: 'symptom',
    phase: 'verification',
    trigger: { kind: 'view', channel: 'metrics', target: 'm-errors' },
    requires: ['e-fix-applied-flag'],
    hint: 'Re-open the error-rate series after the flag change.',
  }),
  node({
    id: 'e-verify-kafka',
    title: 'Kafka lag is draining on its own',
    detail:
      'Consumer lag fell from 48k to 3k without touching Kafka or the consumers, confirming it was a symptom.',
    channel: 'metrics',
    serviceId: 'kafka-payments',
    role: 'symptom',
    phase: 'verification',
    trigger: { kind: 'view', channel: 'metrics', target: 'm-kafka-lag' },
    hint: 'Re-open the Kafka lag series after the fix.',
  }),
]
