import type { ImpactFact, IncidentService } from '@opsforge/types'

export const services: IncidentService[] = [
  {
    id: 'checkout-web',
    name: 'checkout-web',
    kind: 'web',
    dependsOn: ['payment-api'],
    health: 'degraded',
    note: 'Customers see "payment failed" at the final step',
    recoveredNote: 'Checkout completing normally',
    headline: [
      {
        id: 'checkout-success',
        label: 'Checkout success',
        value: '81.6%',
        state: 'crit',
        recovered: { value: '99.7%', state: 'ok' },
      },
    ],
  },
  {
    id: 'payment-api',
    name: 'payment-api',
    kind: 'api',
    dependsOn: [
      'postgres-payments',
      'redis-sessions',
      'kafka-payments',
      'fraud-scoring',
      'psp-gateway',
    ],
    health: 'degraded',
    note: '9 pods Running, readiness passing',
    recoveredNote: '9 pods Running, serving normally',
    headline: [
      {
        id: 'latency',
        label: 'p99 latency',
        value: '8.2 s',
        state: 'crit',
        recovered: { value: '0.31 s', state: 'ok' },
      },
      {
        id: 'errors',
        label: 'Error rate',
        value: '18.4%',
        state: 'crit',
        recovered: { value: '0.3%', state: 'ok' },
      },
      {
        id: 'cpu',
        label: 'CPU',
        value: '42%',
        state: 'ok',
        recovered: { value: '39%', state: 'ok' },
      },
      {
        id: 'db-conn',
        label: 'DB connections',
        value: '98%',
        state: 'crit',
        recovered: { value: '41%', state: 'ok' },
      },
    ],
  },
  {
    id: 'postgres-payments',
    name: 'postgres-payments',
    kind: 'database',
    dependsOn: [],
    health: 'degraded',
    recoveredHealth: 'healthy',
    note: 'Accepting queries; connection slots nearly exhausted',
    recoveredNote: 'Connection usage back to normal',
    headline: [
      {
        id: 'connections',
        label: 'Connections',
        value: '196 / 200',
        state: 'crit',
        recovered: { value: '82 / 200', state: 'ok' },
      },
    ],
  },
  {
    id: 'redis-sessions',
    name: 'redis-sessions',
    kind: 'cache',
    dependsOn: [],
    health: 'healthy',
    note: 'Healthy',
    headline: [{ id: 'hit-ratio', label: 'Hit ratio', value: '97%', state: 'ok' }],
  },
  {
    id: 'kafka-payments',
    name: 'kafka-payments',
    kind: 'queue',
    dependsOn: [],
    health: 'degraded',
    recoveredHealth: 'healthy',
    note: 'Lagging: consumer group payment-events is 48k messages behind',
    recoveredNote: 'Lag draining',
    headline: [
      {
        id: 'lag',
        label: 'Consumer lag',
        value: '48k',
        state: 'crit',
        recovered: { value: '6k', state: 'warn' },
      },
    ],
  },
  {
    id: 'payment-events-consumer',
    name: 'payment-events-consumer',
    kind: 'worker',
    dependsOn: ['kafka-payments', 'postgres-payments'],
    health: 'degraded',
    recoveredHealth: 'healthy',
    note: 'Processing slowly',
    recoveredNote: 'Catching up',
    headline: [],
  },
  {
    id: 'fraud-scoring',
    name: 'fraud-scoring',
    kind: 'api',
    dependsOn: [],
    health: 'healthy',
    note: 'Healthy',
    headline: [],
  },
  {
    id: 'psp-gateway',
    name: 'psp-gateway',
    kind: 'external',
    dependsOn: [],
    health: 'healthy',
    note: 'No incidents reported by the provider',
    headline: [],
  },
  {
    id: 'k8s-platform',
    name: 'k8s-platform',
    kind: 'platform',
    dependsOn: [],
    health: 'healthy',
    note: 'Cluster reports all nodes Ready',
    headline: [],
  },
]

export const impact: ImpactFact[] = [
  {
    id: 'imp-failed',
    label: 'Failed checkouts (last 15 min)',
    value: '≈ 3,900',
    state: 'crit',
    recovered: { value: 'No new failures', state: 'ok' },
  },
  {
    id: 'imp-support',
    label: 'Support tickets',
    value: '212 in 10 min',
    state: 'warn',
    recovered: { value: 'Falling', state: 'ok' },
  },
  {
    id: 'imp-revenue',
    label: 'Revenue at risk',
    value: '≈ $41k per hour',
    state: 'crit',
    gatedBy: 'e-metric-checkout',
    recovered: { value: 'Recovering', state: 'ok' },
  },
  {
    id: 'imp-scope',
    label: 'Affected payment flows',
    value: 'Card payments only. Saved-wallet payments succeed.',
    state: 'warn',
    gatedBy: 'e-trace-wallet',
  },
  {
    id: 'imp-data',
    label: 'Data integrity risk',
    value: 'Failed attempts are rolled back. No double charges observed.',
    state: 'ok',
    gatedBy: 'e-cmd-pg-activity',
  },
]
