import type { LogEntry, LogLevel, MetricSeries, TraceRecord } from '@opsforge/types'

/* One sample per minute, T+00 … T+14 (the candidate is paged at T+14). */

export const metrics: MetricSeries[] = [
  {
    id: 'm-latency',
    serviceId: 'payment-api',
    label: 'p99 request latency',
    unit: 's',
    points: [0.31, 0.31, 0.32, 0.33, 0.34, 0.36, 0.52, 0.9, 1.6, 2.9, 4.3, 5.6, 6.9, 7.7, 8.2],
    recoveredTail: [3.1, 1.2, 0.6, 0.4, 0.31],
    warnAt: 1,
    critAt: 3,
  },
  {
    id: 'm-errors',
    serviceId: 'payment-api',
    label: 'Error rate (5xx)',
    unit: '%',
    points: [0.2, 0.2, 0.2, 0.3, 0.2, 0.3, 0.4, 1.1, 3.0, 6.2, 9.5, 15.0, 16.9, 17.8, 18.4],
    recoveredTail: [7.2, 2.1, 0.8, 0.4, 0.3],
    warnAt: 1,
    critAt: 5,
  },
  {
    id: 'm-cpu',
    serviceId: 'payment-api',
    label: 'CPU utilisation (avg of pods)',
    unit: '%',
    points: [38, 38, 39, 39, 40, 40, 41, 41, 42, 42, 43, 42, 42, 42, 42],
    recoveredTail: [41, 40, 39, 39, 39],
    warnAt: 70,
    critAt: 90,
  },
  {
    id: 'm-traffic',
    serviceId: 'payment-api',
    label: 'Request rate',
    unit: 'req/s',
    points: [612, 640, 655, 648, 660, 652, 648, 655, 650, 658, 645, 652, 649, 655, 648],
    recoveredTail: [650, 652, 649, 655, 651],
  },
  {
    id: 'm-checkout-success',
    serviceId: 'checkout-web',
    label: 'Checkout success rate',
    unit: '%',
    points: [
      99.6, 99.6, 99.7, 99.6, 99.6, 99.5, 99.0, 97.2, 94.1, 90.4, 86.9, 83.8, 82.5, 81.9, 81.6,
    ],
    recoveredTail: [90.2, 96.8, 99.1, 99.6, 99.7],
  },
  {
    id: 'm-db-connections',
    serviceId: 'postgres-payments',
    label: 'Connections in use',
    unit: '%',
    points: [24, 25, 26, 25, 27, 30, 41, 67, 86, 90, 93, 95, 96, 97, 98],
    recoveredTail: [64, 52, 44, 42, 41],
    warnAt: 80,
    critAt: 95,
  },
  {
    id: 'm-db-idle-tx',
    serviceId: 'postgres-payments',
    label: 'Sessions "idle in transaction"',
    unit: 'sessions',
    points: [2, 2, 3, 2, 2, 3, 18, 61, 104, 128, 146, 158, 167, 172, 176],
    recoveredTail: [60, 12, 3, 2, 2],
    warnAt: 20,
    critAt: 50,
  },
  {
    id: 'm-db-cpu',
    serviceId: 'postgres-payments',
    label: 'Database CPU',
    unit: '%',
    points: [28, 28, 29, 29, 30, 30, 31, 31, 31, 32, 31, 31, 31, 31, 31],
    recoveredTail: [30, 29, 29, 28, 28],
    warnAt: 70,
    critAt: 90,
  },
  {
    id: 'm-redis-latency',
    serviceId: 'redis-sessions',
    label: 'Redis p99 latency',
    unit: 'ms',
    points: [0.7, 0.7, 6.8, 3.1, 0.9, 0.8, 0.8, 0.8, 0.8, 0.9, 0.8, 0.8, 0.8, 0.8, 0.8],
    warnAt: 5,
    critAt: 20,
  },
  {
    id: 'm-kafka-lag',
    serviceId: 'kafka-payments',
    label: 'Consumer lag (payment-events)',
    unit: 'k msgs',
    points: [0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.4, 1.8, 7.5, 16, 26, 34, 41, 48],
    recoveredTail: [30, 18, 9, 6, 3],
    warnAt: 5,
    critAt: 20,
  },
]

function t(minute: number, second = 0): number {
  return minute * 60 + second
}

let counter = 0
function log(
  serviceId: string,
  at: number,
  level: LogLevel,
  message: string,
  gatedBy?: string,
): LogEntry {
  counter += 1
  return { id: `log-${counter}`, serviceId, atSeconds: at, level, message, gatedBy }
}

export const logs: LogEntry[] = [
  // payment-api: what an on-call engineer sees without searching.
  log('payment-api', t(13, 2), 'info', 'POST /v1/payments 200 412ms method=card'),
  log('payment-api', t(13, 6), 'warn', 'POST /v1/payments slow request 6240ms method=card'),
  log('payment-api', t(13, 11), 'info', 'POST /v1/payments 200 188ms method=wallet'),
  log(
    'payment-api',
    t(13, 19),
    'error',
    'POST /v1/payments failed: upstream timeout after 8000ms method=card status=504',
  ),
  log(
    'payment-api',
    t(13, 24),
    'error',
    'POST /v1/payments failed: upstream timeout after 8000ms method=card status=504',
  ),
  log('payment-api', t(13, 31), 'info', 'GET /v1/payments/pay_91c2 200 14ms'),
  log(
    'payment-api',
    t(13, 40),
    'error',
    'POST /v1/payments failed: upstream timeout after 8000ms method=card status=504',
  ),
  log('payment-api', t(13, 48), 'info', 'POST /v1/payments 200 205ms method=wallet'),
  log('payment-api', t(13, 55), 'warn', 'POST /v1/payments slow request 7710ms method=card'),
  log(
    'payment-api',
    t(14, 3),
    'error',
    'POST /v1/payments failed: upstream timeout after 8000ms method=card status=504',
  ),
  // Found by searching for connection / pool terms.
  log(
    'payment-api',
    t(8, 41),
    'warn',
    'HikariPool-1 - Connection is not available, request timed out after 30000ms (total=20, active=20, idle=0, waiting=31)',
    'e-log-pool',
  ),
  log(
    'payment-api',
    t(10, 17),
    'error',
    'HikariPool-1 - Connection is not available, request timed out after 30000ms (total=20, active=20, idle=0, waiting=47)',
    'e-log-pool',
  ),
  log(
    'payment-api',
    t(12, 5),
    'error',
    'HikariPool-1 - Connection is not available, request timed out after 30000ms (total=20, active=20, idle=0, waiting=52)',
    'e-log-pool',
  ),
  log(
    'payment-api',
    t(13, 44),
    'error',
    'java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available',
    'e-log-pool',
  ),
  // Found by searching for the pre-authorization flow.
  log(
    'payment-api',
    t(7, 12),
    'info',
    'PreAuthHoldService: BEGIN tx order=ord_81f2 conn=conn-17 (held until commit)',
    'e-log-preauth',
  ),
  log(
    'payment-api',
    t(9, 33),
    'warn',
    'PreAuthHoldService: tx open 4410ms waiting for a second connection for the audit write order=ord_77aa conn=conn-3',
    'e-log-preauth',
  ),
  log(
    'payment-api',
    t(11, 50),
    'warn',
    'PreAuthHoldService: tx open 7912ms waiting for a second connection for the audit write order=ord_6c01 pool active=20/20',
    'e-log-preauth',
  ),
  log(
    'payment-api',
    t(13, 8),
    'warn',
    'PreAuthHoldService: holding conn-9 while acquiring audit connection; commit deferred order=ord_3de9',
    'e-log-preauth',
  ),

  log('postgres-payments', t(13, 5), 'info', 'checkpoint complete: wrote 412 buffers (2.5%)'),
  log(
    'postgres-payments',
    t(13, 29),
    'info',
    'duration: 3.2 ms  statement: select id, status from payments where id = $1',
  ),
  log(
    'postgres-payments',
    t(13, 51),
    'info',
    'automatic vacuum of table "payments.preauth_holds": index scans: 0',
  ),
  log(
    'postgres-payments',
    t(10, 4),
    'error',
    'FATAL: remaining connection slots are reserved for non-replication superuser connections',
    'e-log-pg-slots',
  ),
  log(
    'postgres-payments',
    t(12, 31),
    'error',
    'FATAL: remaining connection slots are reserved for non-replication superuser connections',
    'e-log-pg-slots',
  ),
  log(
    'postgres-payments',
    t(13, 36),
    'error',
    'FATAL: sorry, too many clients already',
    'e-log-pg-slots',
  ),

  log('payment-events-consumer', t(12, 40), 'warn', 'batch commit slow: 11240ms (batch=500)'),
  log(
    'payment-events-consumer',
    t(13, 12),
    'error',
    'batch commit timed out after 14000ms; will retry offset=8841200 partition=3',
    'e-log-consumer',
  ),
  log(
    'payment-events-consumer',
    t(13, 40),
    'error',
    'could not obtain database connection for settlement write; retrying in 5s',
    'e-log-consumer',
  ),

  log('redis-sessions', t(2, 4), 'warn', 'Background saving started by pid 4121 (fork took 6 ms)'),
  log('redis-sessions', t(2, 9), 'info', 'Background saving terminated with success'),
  log('redis-sessions', t(13, 0), 'info', 'DB 0: 1204811 keys (expires: 1204811)'),

  log(
    'kafka-payments',
    t(13, 15),
    'info',
    'Group coordinator: group payment-events-consumer stable, generation 41',
  ),
  log('kafka-payments', t(13, 42), 'info', 'ISR for payment-events-2 unchanged (3 of 3)'),

  log('psp-gateway', t(13, 1), 'info', 'POST /authorize 200 288ms'),
  log('psp-gateway', t(13, 28), 'info', 'POST /authorize 200 312ms'),
  log('psp-gateway', t(13, 53), 'info', 'POST /authorize 200 301ms'),

  log('fraud-scoring', t(13, 10), 'info', 'score request 21ms decision=allow'),
  log('fraud-scoring', t(13, 37), 'info', 'score request 24ms decision=allow'),

  log(
    'k8s-platform',
    t(4, 8),
    'info',
    'Node ip-10-0-3-17 cordoned and drained by cluster-autoscaler (scale-down)',
  ),
  log(
    'k8s-platform',
    t(4, 51),
    'info',
    'Pod payment-api-7b8c6d9f4-q9m2z rescheduled onto ip-10-0-5-42',
  ),
  log('k8s-platform', t(5, 30), 'info', 'Node ip-10-0-3-22 Ready'),

  log(
    'checkout-web',
    t(13, 20),
    'error',
    'payment step failed: payment-api returned 504 (retry offered to customer)',
  ),
  log(
    'checkout-web',
    t(13, 45),
    'error',
    'payment step failed: payment-api returned 504 (retry offered to customer)',
  ),
]

export const traces: TraceRecord[] = [
  {
    id: 'tr-slow-1',
    serviceId: 'payment-api',
    operation: 'POST /v1/payments (card)',
    atSeconds: t(13, 6),
    durationMs: 6240,
    status: 'ok',
    spans: [
      {
        id: 's1',
        serviceId: 'payment-api',
        operation: 'POST /v1/payments',
        startMs: 0,
        durationMs: 6240,
        status: 'ok',
      },
      {
        id: 's2',
        parentId: 's1',
        serviceId: 'fraud-scoring',
        operation: 'POST /score',
        startMs: 8,
        durationMs: 22,
        status: 'ok',
      },
      {
        id: 's3',
        parentId: 's1',
        serviceId: 'payment-api',
        operation: 'db.acquire_connection',
        startMs: 34,
        durationMs: 5710,
        status: 'ok',
        tags: { 'pool.name': 'HikariPool-1', 'pool.waiting': '47' },
      },
      {
        id: 's4',
        parentId: 's1',
        serviceId: 'postgres-payments',
        operation: 'INSERT payments',
        startMs: 5748,
        durationMs: 6,
        status: 'ok',
      },
      {
        id: 's5',
        parentId: 's1',
        serviceId: 'redis-sessions',
        operation: 'GET session',
        startMs: 5760,
        durationMs: 1,
        status: 'ok',
      },
      {
        id: 's6',
        parentId: 's1',
        serviceId: 'kafka-payments',
        operation: 'produce payment.created',
        startMs: 5764,
        durationMs: 9,
        status: 'ok',
      },
    ],
  },
  {
    id: 'tr-slow-2',
    serviceId: 'payment-api',
    operation: 'POST /v1/payments (card) · preauth',
    atSeconds: t(13, 19),
    durationMs: 7840,
    status: 'ok',
    spans: [
      {
        id: 's1',
        serviceId: 'payment-api',
        operation: 'POST /v1/payments',
        startMs: 0,
        durationMs: 7840,
        status: 'ok',
      },
      {
        id: 's2',
        parentId: 's1',
        serviceId: 'fraud-scoring',
        operation: 'POST /score',
        startMs: 7,
        durationMs: 21,
        status: 'ok',
      },
      {
        id: 's3',
        parentId: 's1',
        serviceId: 'payment-api',
        operation: 'db.acquire_connection',
        startMs: 33,
        durationMs: 3920,
        status: 'ok',
        tags: { 'pool.waiting': '49' },
      },
      {
        id: 's4',
        parentId: 's1',
        serviceId: 'payment-api',
        operation: 'db.tx(preauth_hold)',
        startMs: 3960,
        durationMs: 3850,
        status: 'ok',
        tags: { 'tx.state': 'open', 'connections.held': '1' },
      },
      {
        id: 's5',
        parentId: 's4',
        serviceId: 'postgres-payments',
        operation: 'SELECT … FROM preauth_holds FOR UPDATE',
        startMs: 3968,
        durationMs: 4,
        status: 'ok',
      },
      {
        id: 's6',
        parentId: 's4',
        serviceId: 'payment-api',
        operation: 'db.acquire_connection (audit_log)',
        startMs: 3975,
        durationMs: 3790,
        status: 'ok',
        tags: { 'pool.waiting': '49', 'connections.held': '1' },
      },
      {
        id: 's7',
        parentId: 's4',
        serviceId: 'postgres-payments',
        operation: 'INSERT audit_log',
        startMs: 7768,
        durationMs: 3,
        status: 'ok',
      },
      {
        id: 's8',
        parentId: 's4',
        serviceId: 'postgres-payments',
        operation: 'COMMIT',
        startMs: 7806,
        durationMs: 3,
        status: 'ok',
      },
    ],
  },
  {
    id: 'tr-err-1',
    serviceId: 'payment-api',
    operation: 'POST /v1/payments (card)',
    atSeconds: t(13, 24),
    durationMs: 8004,
    status: 'error',
    spans: [
      {
        id: 's1',
        serviceId: 'payment-api',
        operation: 'POST /v1/payments',
        startMs: 0,
        durationMs: 8004,
        status: 'error',
        tags: { 'http.status': '504' },
      },
      {
        id: 's2',
        parentId: 's1',
        serviceId: 'fraud-scoring',
        operation: 'POST /score',
        startMs: 6,
        durationMs: 23,
        status: 'ok',
      },
      {
        id: 's3',
        parentId: 's1',
        serviceId: 'payment-api',
        operation: 'db.acquire_connection',
        startMs: 33,
        durationMs: 7960,
        status: 'error',
        tags: { error: 'timeout waiting for a pooled connection' },
      },
    ],
  },
  {
    id: 'tr-wallet-ok',
    serviceId: 'payment-api',
    operation: 'POST /v1/payments (wallet)',
    atSeconds: t(13, 11),
    durationMs: 188,
    status: 'ok',
    spans: [
      {
        id: 's1',
        serviceId: 'payment-api',
        operation: 'POST /v1/payments',
        startMs: 0,
        durationMs: 188,
        status: 'ok',
      },
      {
        id: 's2',
        parentId: 's1',
        serviceId: 'redis-sessions',
        operation: 'GET session',
        startMs: 4,
        durationMs: 1,
        status: 'ok',
      },
      {
        id: 's3',
        parentId: 's1',
        serviceId: 'payment-api',
        operation: 'db.acquire_connection',
        startMs: 7,
        durationMs: 3,
        status: 'ok',
      },
      {
        id: 's4',
        parentId: 's1',
        serviceId: 'postgres-payments',
        operation: 'INSERT payments',
        startMs: 12,
        durationMs: 5,
        status: 'ok',
      },
      {
        id: 's5',
        parentId: 's1',
        serviceId: 'kafka-payments',
        operation: 'produce payment.created',
        startMs: 168,
        durationMs: 14,
        status: 'ok',
      },
    ],
  },
]
