import type { QuestionSpec } from '@opsforge/types'
import { concept, question } from './author'

const ARCH_SIGNALS = ['requirements', 'failure-modes', 'tradeoff', 'scalability'] as const

export const architectureQuestions: QuestionSpec[] = [
  question({
    id: 'arch-ha-web',
    rounds: ['architecture'],
    topic: 'architecture',
    technologies: ['aws', 'kubernetes', 'load-balancer'],
    difficulty: 'senior',
    prompt:
      'Design a highly available web application on a cloud of your choice. Start with the questions you would ask me, then talk me through the design.',
    intent:
      'Rewards asking for requirements first, then removing single points of failure with explicit trade-offs.',
    expectedSignals: [...ARCH_SIGNALS],
    wordRange: [120, 400],
    maxFollowUps: 3,
    concepts: [
      concept(
        'requirements',
        'Clarify requirements and targets',
        'Availability target, traffic profile, data sensitivity, RTO/RPO and budget shape the design.',
        [
          'requirements',
          'availability target',
          'rto',
          'rpo',
          'traffic',
          'slo',
          'budget',
          'constraints',
          'users',
        ],
        'What do you need to know about the system before you draw anything?',
        { w: 3 },
      ),
      concept(
        'multi-az',
        'Spread across failure domains',
        'Instances in at least two availability zones behind a load balancer, with health checks.',
        [
          'availability zone',
          'multi-az',
          'multi az',
          'az ',
          'zones',
          'load balancer',
          'health check',
          'failure domain',
        ],
        'What single thing failing today would take your design down?',
        { w: 3 },
      ),
      concept(
        'stateless-scale',
        'Stateless tier and autoscaling',
        'Stateless application servers scale horizontally; sessions live outside the instance.',
        ['stateless', 'autoscal', 'horizontal', 'session', 'scale out', 'auto scaling'],
        'How does this cope when traffic doubles in ten minutes?',
        { w: 2 },
      ),
      concept(
        'data-tier',
        'Resilient data tier',
        'A managed database with synchronous standby or replicas, backups and tested failover.',
        [
          'replica',
          'standby',
          'failover',
          'backup',
          'multi-az database',
          'rds',
          'aurora',
          'point-in-time',
          'replication',
        ],
        'Where does the data live, and what happens to it when its host dies?',
        { w: 3 },
      ),
      concept(
        'release-safety',
        'Safe deployment and rollback',
        'Rolling or blue/green releases keep deploys from being the main source of downtime.',
        ['blue/green', 'blue green', 'canary', 'rolling', 'rollback', 'zero downtime', 'deploy'],
        'Deploys cause more outages than hardware. How do you make them safe?',
        { w: 2 },
      ),
      concept(
        'observe-test',
        'Observability and failure testing',
        'SLO-based monitoring and game days prove the redundancy works.',
        ['monitor', 'slo', 'alert', 'chaos', 'game day', 'load test', 'failover test', 'observab'],
        'How would you know the redundancy actually works before a real failure?',
        { w: 2 },
      ),
      concept(
        'cost-tradeoff',
        'Cost versus availability',
        'Each extra nine costs more; the design should match what the business actually needs.',
        ['cost', 'trade-off', 'tradeoff', 'budget', 'worth', 'complexity', 'diminishing'],
        'What would you simplify if the budget were cut in half?',
        { w: 2, kind: 'tradeoff' },
      ),
    ],
  }),
  question({
    id: 'arch-zero-downtime',
    rounds: ['architecture', 'technical'],
    topic: 'ci-cd',
    technologies: ['kubernetes', 'ci-cd', 'database'],
    difficulty: 'senior',
    prompt:
      'Design a deployment strategy for a service that cannot have downtime and includes a breaking database schema change.',
    intent: 'Tests expand/contract migrations, release strategy and backward compatibility.',
    expectedSignals: ['failure-modes', 'tradeoff', 'structured'],
    wordRange: [100, 380],
    maxFollowUps: 3,
    concepts: [
      concept(
        'expand-contract',
        'Expand and contract migrations',
        'Add new schema in a backwards-compatible way, migrate, switch code, then remove the old schema later.',
        [
          'expand',
          'contract',
          'backward compatible',
          'backwards compatible',
          'additive',
          'two-phase',
          'multi-step',
          'dual write',
        ],
        'Old and new code run at the same time during a rollout. What does that mean for the schema change?',
        { w: 3 },
      ),
      concept(
        'progressive-release',
        'Progressive release',
        'Canary or blue/green with automated analysis limits who is affected.',
        [
          'canary',
          'blue/green',
          'blue green',
          'progressive',
          'traffic shifting',
          'feature flag',
          'argo rollouts',
        ],
        'How do you limit the number of users exposed to a bad release?',
        { w: 3 },
      ),
      concept(
        'rollback-plan',
        'Rollback that works with data',
        'Rollback must be safe once data has been written in the new shape, so migrations are reversible or compatible.',
        [
          'rollback',
          'roll back',
          'revert',
          'reversible',
          'down migration',
          'forward fix',
          'previous version',
        ],
        'The new version is bad after the migration ran. What do you do?',
        { w: 3 },
      ),
      concept(
        'online-migration',
        'Online migration of large tables',
        'Batching, online schema-change tools and avoiding long locks keep the database responsive.',
        [
          'lock',
          'batch',
          'backfill',
          'gh-ost',
          'pt-online',
          'concurrently',
          'online schema',
          'long running',
        ],
        'The table has 500 million rows. What could go wrong while changing it?',
        { w: 2 },
      ),
      concept(
        'health-gates',
        'Health gates and drain',
        'Readiness checks, graceful shutdown and automated verification gate each step.',
        [
          'readiness',
          'health check',
          'graceful',
          'drain',
          'smoke test',
          'automated analysis',
          'gate',
        ],
        'What decides that a step of the rollout is safe to continue?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'arch-multi-region-dr',
    rounds: ['architecture'],
    topic: 'architecture',
    technologies: ['aws', 'dns', 'database'],
    difficulty: 'staff',
    prompt:
      'The business wants to survive the loss of an entire cloud region. Design the disaster recovery approach, including the trade-offs between options.',
    intent:
      'Checks for RTO/RPO-driven choice between backup, pilot light, warm standby and active-active, with data consistency in mind.',
    expectedSignals: ['requirements', 'failure-modes', 'tradeoff', 'cost'],
    wordRange: [120, 420],
    maxFollowUps: 3,
    concepts: [
      concept(
        'rto-rpo',
        'RTO and RPO drive the choice',
        'Recovery time and data-loss tolerance, agreed with the business, decide how much to spend.',
        [
          'rto',
          'rpo',
          'recovery time',
          'recovery point',
          'data loss',
          'tolerance',
          'business impact',
        ],
        'How do you decide how much redundancy is enough?',
        { w: 3 },
      ),
      concept(
        'dr-tiers',
        'Known DR strategies',
        'Backup and restore, pilot light, warm standby and active-active trade cost against recovery time.',
        [
          'pilot light',
          'warm standby',
          'active-active',
          'active active',
          'active-passive',
          'backup and restore',
          'cold standby',
        ],
        'What are the options on the spectrum from cheapest to most resilient?',
        { w: 3 },
      ),
      concept(
        'data-replication',
        'Cross-region data replication',
        'Asynchronous replication risks data loss; synchronous adds latency. Conflicts matter for active-active.',
        [
          'replication',
          'cross-region',
          'asynchronous',
          'synchronous',
          'global database',
          'conflict',
          'eventual',
          'consistency',
        ],
        'Where does the data go, and what could you lose?',
        { w: 3 },
      ),
      concept(
        'traffic-failover',
        'Traffic failover',
        'DNS failover or global load balancing with health checks; TTLs and clients caching matter.',
        [
          'dns',
          'route 53',
          'failover',
          'global load balanc',
          'anycast',
          'ttl',
          'health check',
          'traffic',
        ],
        'How do users end up in the other region?',
        { w: 2 },
      ),
      concept(
        'dr-testing',
        'Regular failover testing',
        'Untested DR does not work: game days, runbooks, and failback planning.',
        ['test', 'game day', 'drill', 'runbook', 'failback', 'exercise', 'chaos'],
        'How do you know it will work at 3am?',
        { w: 3 },
      ),
      concept(
        'dr-cost',
        'Cost and complexity trade-off',
        'Active-active is expensive and complex; many systems are better served by warm standby.',
        ['cost', 'complexity', 'expensive', 'trade-off', 'tradeoff', 'worth it', 'overkill'],
        'When would active-active be the wrong call?',
        { w: 2, kind: 'tradeoff' },
      ),
    ],
  }),
  question({
    id: 'arch-multi-account-identity',
    rounds: ['architecture'],
    topic: 'security',
    technologies: ['aws', 'iam', 'terraform'],
    difficulty: 'staff',
    prompt:
      'Design the account structure and identity model for a growing company on AWS: multiple teams, production isolation and auditability.',
    intent:
      'Landing zone thinking: account boundaries, SSO, guardrails, logging and delegated administration.',
    expectedSignals: ['requirements', 'security', 'tradeoff'],
    wordRange: [100, 380],
    maxFollowUps: 3,
    concepts: [
      concept(
        'account-boundaries',
        'Multiple accounts as isolation boundaries',
        'Separate accounts per environment, workload and function (security, logging, shared services).',
        [
          'multi-account',
          'multiple accounts',
          'organizations',
          'account per',
          'separate accounts',
          'blast radius',
          'landing zone',
          'control tower',
        ],
        'Why not run everything in one account with careful IAM?',
        { w: 3 },
      ),
      concept(
        'central-sso',
        'Central identity with SSO',
        'Federated single sign-on with short-lived role sessions, not IAM users with long-lived keys.',
        ['sso', 'identity center', 'federat', 'idp', 'okta', 'saml', 'oidc', 'no iam users'],
        'How do engineers authenticate, and what credentials do they hold?',
        { w: 3 },
      ),
      concept(
        'guardrails',
        'Preventive guardrails',
        'SCPs and permission boundaries stop dangerous actions regardless of account-level policies.',
        [
          'scp',
          'service control',
          'guardrail',
          'permission boundary',
          'deny',
          'policy as code',
          'preventive',
        ],
        'How do you stop a team from doing something dangerous even if they are admin in their account?',
        { w: 3 },
      ),
      concept(
        'audit-logging',
        'Centralised audit and logging',
        'Organisation-wide CloudTrail, config and logs go to a protected log archive account.',
        [
          'cloudtrail',
          'log archive',
          'audit',
          'config',
          'centralized logging',
          'immutable',
          'guardduty',
          'security hub',
        ],
        'How would you reconstruct who did what across all accounts?',
        { w: 2 },
      ),
      concept(
        'automation-provisioning',
        'Automated account provisioning',
        'Accounts and baseline controls are vended through code so every account starts compliant.',
        [
          'account factory',
          'baseline',
          'terraform',
          'automation',
          'vending',
          'iac',
          'template',
          'provision',
        ],
        'A new team needs an environment tomorrow. How does that happen without manual setup?',
        { w: 2 },
      ),
      concept(
        'access-tradeoff',
        'Autonomy versus control',
        'Too many guardrails slow teams down; too few create risk. The design needs an exception path.',
        [
          'autonomy',
          'friction',
          'self-service',
          'exception',
          'trade-off',
          'tradeoff',
          'developer experience',
          'balance',
        ],
        'Where does this make life harder for engineers, and what do you do about it?',
        { w: 2, kind: 'tradeoff' },
      ),
    ],
  }),
  question({
    id: 'arch-observability-platform',
    rounds: ['architecture'],
    topic: 'observability',
    technologies: ['prometheus', 'opentelemetry', 'grafana', 'kubernetes'],
    difficulty: 'senior',
    prompt:
      'You are asked to build an observability platform for 80 microservices. What do you build, and what do you deliberately leave out?',
    intent: 'Looks for signal strategy, cost control and adoption, not a list of tools.',
    expectedSignals: ['requirements', 'tradeoff', 'cost', 'observability'],
    wordRange: [100, 380],
    maxFollowUps: 3,
    concepts: [
      concept(
        'three-signals',
        'Metrics, logs and traces',
        'Each signal answers different questions, and they should correlate through shared identifiers.',
        ['metrics', 'logs', 'traces', 'three pillars', 'correlat', 'trace id', 'exemplar'],
        'What kinds of questions do you need to be able to answer in an incident?',
        { w: 3 },
      ),
      concept(
        'standard-instrumentation',
        'Standardised instrumentation',
        'OpenTelemetry and shared libraries give consistent telemetry without every team reinventing it.',
        [
          'opentelemetry',
          'otel',
          'sdk',
          'standard',
          'instrumentation',
          'library',
          'collector',
          'semantic convention',
        ],
        'How do 80 teams end up emitting comparable data?',
        { w: 3 },
      ),
      concept(
        'cardinality-cost',
        'Cardinality and cost control',
        'High-cardinality labels and verbose logs drive cost; sampling, retention tiers and quotas manage it.',
        ['cardinality', 'sampling', 'retention', 'cost', 'quota', 'tiered', 'downsampl', 'drop'],
        'The bill doubles after a team adds a user_id label. What do you do about it?',
        { w: 3, kind: 'tradeoff' },
      ),
      concept(
        'slo-alerting',
        'SLO-driven alerting and dashboards',
        'Standard SLOs and golden-signal dashboards give each service a consistent starting point.',
        ['slo', 'golden signals', 'red method', 'use method', 'dashboard', 'burn rate', 'alert'],
        'What does a team get out of the box for a new service?',
        { w: 2 },
      ),
      concept(
        'reliability-platform',
        'Reliability of the platform itself',
        'The monitoring stack needs its own availability, with a separate path for alerting on its failure.',
        [
          'monitor the monitor',
          'meta-monitoring',
          'dead man',
          'watchdog',
          'high availability',
          'federat',
          'redundan',
        ],
        'What happens when your observability platform is down during an incident?',
        { w: 2 },
      ),
      concept(
        'adoption',
        'Adoption over perfection',
        'A platform nobody uses fails; self-service, defaults and documentation drive adoption.',
        [
          'adoption',
          'self-service',
          'defaults',
          'documentation',
          'onboarding',
          'paved',
          'enablement',
          'templates',
        ],
        'How do you make sure teams actually use it?',
        { w: 1 },
      ),
    ],
  }),
]
