import type { QuestionSpec } from '@opsforge/types'
import { concept, question } from './author'

const STAR = ['situation', 'action', 'result', 'ownership'] as const

export const behavioralQuestions: QuestionSpec[] = [
  question({
    id: 'beh-incident-led',
    rounds: ['behavioral'],
    topic: 'incident-response',
    technologies: ['sre', 'on-call'],
    difficulty: 'senior',
    prompt:
      'Tell me about a serious production incident you personally led or were central to resolving.',
    intent: 'Seeks a real story with ownership, calm structure, communication and a lasting fix.',
    expectedSignals: [...STAR, 'communication-plan', 'prevention', 'reflection'],
    wordRange: [120, 380],
    emphasis: { 'incident-response': 2 },
    concepts: [
      concept(
        'impact-context',
        'Concrete context and impact',
        'What broke, who was affected and how badly.',
        [
          'customers',
          'users affected',
          'revenue',
          'outage',
          'minutes',
          'impact',
          'sev',
          'p1',
          'downtime',
        ],
        'How bad was it, and for whom?',
        { w: 2 },
      ),
      concept(
        'my-actions',
        'Specific personal actions',
        'What the candidate themselves did, not what the team did.',
        [
          'i decided',
          'i led',
          'i ran',
          'i rolled',
          'i checked',
          'i found',
          'i took',
          'my role',
          'i was the',
        ],
        'What did you personally do, as opposed to the team?',
        { w: 3 },
      ),
      concept(
        'coordination',
        'Coordination and communication',
        'Roles, status updates and stakeholder communication kept the response orderly.',
        [
          'incident commander',
          'status',
          'updated',
          'stakeholder',
          'communicat',
          'war room',
          'bridge',
          'slack channel',
          'roles',
        ],
        'How did you keep everyone else informed and organised while it was happening?',
        { w: 2 },
      ),
      concept(
        'resolution-outcome',
        'Resolution and measured outcome',
        'How it was resolved and what changed afterwards, ideally with numbers.',
        ['resolved', 'restored', 'recovered', 'mttr', 'reduced', 'minutes to', 'rollback', 'fixed'],
        'How did it end, and how do you know it was actually resolved?',
        { w: 3 },
      ),
      concept(
        'lasting-fix',
        'Postmortem and prevention',
        'A blameless review produced concrete changes that were delivered.',
        [
          'postmortem',
          'post-mortem',
          'blameless',
          'action item',
          'prevent',
          'alert',
          'runbook',
          'follow-up',
          'root cause',
        ],
        'What changed afterwards so it would not happen again?',
        { w: 3 },
      ),
    ],
  }),
  question({
    id: 'beh-disagreement',
    rounds: ['behavioral'],
    topic: 'leadership',
    technologies: [],
    difficulty: 'senior',
    prompt:
      'Describe a time you strongly disagreed with a colleague or lead about a technical decision. What happened?',
    intent: 'Looks for evidence-based persuasion, respect, and committing to the outcome.',
    expectedSignals: [...STAR, 'reflection'],
    wordRange: [100, 340],
    concepts: [
      concept(
        'position-evidence',
        'Argued with evidence',
        'Data, a prototype or a clear risk analysis rather than opinion.',
        [
          'data',
          'evidence',
          'benchmark',
          'prototype',
          'proof of concept',
          'poc',
          'measured',
          'risk',
          'numbers',
        ],
        'How did you try to show your point rather than just assert it?',
        { w: 3 },
      ),
      concept(
        'understood-other',
        'Understood the other side',
        'Took the other view seriously and found what was valid in it.',
        [
          'their concern',
          'their point',
          'listened',
          'understand',
          'perspective',
          'valid',
          'asked why',
          'constraint',
        ],
        'What was the strongest part of the other person’s argument?',
        { w: 2 },
      ),
      concept(
        'resolution',
        'How it was resolved',
        'A decision mechanism: experiment, decision record, escalation, or compromise.',
        [
          'adr',
          'decision record',
          'agreed',
          'compromise',
          'escalat',
          'decided',
          'experiment',
          'trial',
          'timebox',
        ],
        'How was the disagreement finally settled?',
        { w: 3 },
      ),
      concept(
        'commit-support',
        'Disagree and commit',
        'Supported the decision wholeheartedly even when not the one they preferred.',
        ['disagree and commit', 'supported', 'committed', 'moved on', 'backed', 'went with'],
        'If the decision went against you, what did you do next?',
        { w: 2 },
      ),
      concept(
        'relationship-lesson',
        'Relationship and lesson',
        'The relationship held and the candidate would handle it better or the same next time.',
        ['relationship', 'trust', 'learned', 'next time', 'differently', 'afterwards'],
        'What did you learn, and what is the relationship like now?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'beh-mistake',
    rounds: ['behavioral', 'final'],
    topic: 'behavioral',
    technologies: [],
    difficulty: 'senior',
    prompt: 'Tell me about a significant mistake you made in production and what you did about it.',
    intent:
      'Rewards honesty, ownership without blame-shifting, fast recovery and systemic learning.',
    expectedSignals: [...STAR, 'reflection', 'prevention'],
    wordRange: [100, 340],
    concepts: [
      concept(
        'honest-ownership',
        'Owns the mistake plainly',
        'Says what they did wrong without deflecting.',
        [
          'my mistake',
          'i made',
          'i missed',
          'i should have',
          'i ran',
          'my fault',
          'i caused',
          'i forgot',
          'i assumed',
        ],
        'What exactly was your part in it?',
        { w: 3 },
      ),
      concept(
        'recovery',
        'Detection and recovery',
        'How it was noticed, contained and fixed.',
        [
          'noticed',
          'detected',
          'alert',
          'rolled back',
          'restored',
          'recovered',
          'contained',
          'told',
          'escalated',
        ],
        'How did you find out, and what did you do in the first few minutes?',
        { w: 3 },
      ),
      concept(
        'transparency',
        'Told people quickly',
        'Immediate transparency to the team and stakeholders.',
        [
          'told',
          'informed',
          'raised',
          'flagged',
          'transparen',
          'announced',
          'owned up',
          'let the team know',
        ],
        'Who did you tell, and how quickly?',
        { w: 2 },
      ),
      concept(
        'systemic-fix',
        'Fixed the system, not just the person',
        'Guardrails, review steps or automation so the same mistake is hard to repeat.',
        [
          'guardrail',
          'automation',
          'process',
          'checklist',
          'review',
          'safeguard',
          'confirmation',
          'dry run',
          'policy',
          'permission',
        ],
        'What did you change so the next person could not make the same mistake?',
        { w: 3 },
      ),
      concept(
        'lesson',
        'A concrete lesson',
        'A specific change in how they work now.',
        ['learned', 'now i', 'since then', 'lesson', 'differently', 'habit', 'always'],
        'What do you do differently today because of it?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'beh-toil',
    rounds: ['behavioral'],
    topic: 'sre',
    technologies: ['automation'],
    difficulty: 'intermediate',
    prompt:
      'Tell me about a time you identified and removed significant operational toil. How did you decide it was worth it?',
    intent: 'Probes prioritisation, measurement and follow-through on automation.',
    expectedSignals: [...STAR, 'metric'],
    wordRange: [90, 320],
    concepts: [
      concept(
        'measured-problem',
        'Quantified the toil',
        'Time spent, frequency or error rate showed the problem was real.',
        [
          'hours',
          'per week',
          'per month',
          'times a',
          'measured',
          'tracked',
          'ticket',
          'frequency',
          'percent',
        ],
        'How did you know how big the problem was?',
        { w: 3 },
      ),
      concept(
        'prioritised',
        'Weighed cost against payoff',
        'Compared build effort with time saved and risk reduced.',
        [
          'payback',
          'worth',
          'roi',
          'effort',
          'break even',
          'prioriti',
          'tradeoff',
          'trade-off',
          'cost of',
        ],
        'Why was this the thing to automate and not something else?',
        { w: 2, kind: 'tradeoff' },
      ),
      concept(
        'solution',
        'What was built',
        'A concrete automation or platform change, built iteratively.',
        [
          'automated',
          'script',
          'pipeline',
          'self-service',
          'terraform',
          'operator',
          'bot',
          'tool',
          'built',
        ],
        'What did you actually build?',
        { w: 3 },
      ),
      concept(
        'adoption-result',
        'Adoption and measured result',
        'People used it and the numbers changed.',
        ['adopted', 'teams use', 'reduced', 'saved', 'down from', 'dropped', 'feedback', 'usage'],
        'Did it work, and how do you know?',
        { w: 3 },
      ),
    ],
  }),
  question({
    id: 'beh-mentoring',
    rounds: ['behavioral', 'final'],
    topic: 'leadership',
    technologies: [],
    difficulty: 'senior',
    prompt: 'Tell me about a time you raised the capability of someone or a team around you.',
    intent:
      'Senior roles multiply others. Looks for specific, sustained enablement rather than doing the work for them.',
    expectedSignals: [...STAR, 'reflection'],
    wordRange: [90, 320],
    concepts: [
      concept(
        'diagnosed-need',
        'Diagnosed what was needed',
        'Understood the person or team’s gap before acting.',
        ['gap', 'struggl', 'needed', 'asked', 'noticed', 'assess', 'pairing', 'one-on-one', '1:1'],
        'How did you work out what they actually needed?',
        { w: 2 },
      ),
      concept(
        'enablement-method',
        'A deliberate method',
        'Pairing, documentation, runbooks, reviews or delegation with support.',
        [
          'pair',
          'shadow',
          'documentation',
          'workshop',
          'runbook',
          'review',
          'delegat',
          'guide',
          'coaching',
          'game day',
        ],
        'What did you do, specifically, rather than doing it for them?',
        { w: 3 },
      ),
      concept(
        'lasting-change',
        'Lasting change',
        'The capability remained after the mentor stepped back.',
        [
          'independent',
          'on their own',
          'stepped back',
          'owns it',
          'now leads',
          'sustain',
          'handed over',
          'still',
        ],
        'What happened when you stopped being involved?',
        { w: 3 },
      ),
      concept(
        'outcome-evidence',
        'Evidence of impact',
        'Promotion, reduced escalations, faster delivery, or similar.',
        [
          'promoted',
          'escalations',
          'faster',
          'reduced',
          'on-call',
          'confidence',
          'results',
          'measur',
        ],
        'How did you know it had worked?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'beh-influence',
    rounds: ['behavioral', 'final'],
    topic: 'leadership',
    technologies: [],
    difficulty: 'staff',
    prompt:
      'Tell me about a time you drove a significant change in how engineering worked without having authority over the people involved.',
    intent:
      'Staff-level influence: building a case, aligning stakeholders and sustaining adoption.',
    expectedSignals: [...STAR, 'tradeoff', 'reflection'],
    wordRange: [110, 360],
    concepts: [
      concept(
        'business-case',
        'Built the case',
        'Connected the change to outcomes teams and leadership cared about.',
        [
          'business case',
          'incident',
          'cost',
          'risk',
          'rfc',
          'proposal',
          'data showed',
          'pitch',
          'problem statement',
          'why now',
        ],
        'How did you convince people it was worth their time?',
        { w: 3 },
      ),
      concept(
        'stakeholders',
        'Aligned stakeholders',
        'Found the early adopters and objectors, and addressed their concerns.',
        [
          'stakeholder',
          'sponsor',
          'early adopter',
          'objection',
          'concern',
          'buy-in',
          'champion',
          'pilot team',
          'allies',
        ],
        'Who pushed back, and what did you do about it?',
        { w: 3 },
      ),
      concept(
        'incremental-rollout',
        'Rolled out incrementally',
        'A pilot, defaults and migration support rather than a mandate.',
        [
          'pilot',
          'incremental',
          'phase',
          'migration',
          'paved road',
          'default',
          'opt-in',
          'rollout plan',
        ],
        'How did you get from one team to many?',
        { w: 2 },
      ),
      concept(
        'sustained',
        'Sustained after launch',
        'Metrics, ownership and documentation kept the change alive.',
        [
          'sustain',
          'metrics',
          'adoption',
          'ownership',
          'maintain',
          'documentation',
          'still used',
          'standard',
        ],
        'What kept it from decaying once you moved on?',
        { w: 2 },
      ),
    ],
  }),
]
