import type { QuestionSpec } from '@opsforge/types'
import { concept, question } from './author'

export const finalQuestions: QuestionSpec[] = [
  question({
    id: 'fin-first-90',
    rounds: ['final'],
    topic: 'leadership',
    technologies: [],
    difficulty: 'senior',
    prompt:
      'You join as a senior DevOps engineer in a team with frequent incidents and slow releases. What do you do in your first ninety days?',
    intent:
      'Looks for listen-first, evidence-led prioritisation, early wins and a plan, not a tool shopping list.',
    expectedSignals: ['structured', 'tradeoff', 'requirements'],
    wordRange: [100, 360],
    concepts: [
      concept(
        'listen-first',
        'Learn before changing',
        'Understand the system, the people and the pain before prescribing solutions.',
        [
          'listen',
          'learn',
          'understand',
          'interview',
          'shadow',
          'on-call',
          'read the postmortems',
          'first month',
          'observe',
        ],
        'What do you do before you change anything?',
        { w: 3 },
      ),
      concept(
        'data-prioritise',
        'Prioritise with evidence',
        'Use incident history, DORA-style metrics and toil data to choose what matters most.',
        [
          'data',
          'metrics',
          'dora',
          'incident history',
          'postmortem',
          'lead time',
          'change failure',
          'baseline',
          'prioriti',
        ],
        'How do you decide what to tackle first?',
        { w: 3 },
      ),
      concept(
        'early-win',
        'Deliver an early, visible win',
        'A small, valuable fix builds trust and momentum.',
        [
          'quick win',
          'early win',
          'small win',
          'low-hanging',
          'trust',
          'momentum',
          'credibility',
          'visible',
        ],
        'What would you aim to deliver in the first few weeks, and why that?',
        { w: 2 },
      ),
      concept(
        'build-with-team',
        'Bring the team along',
        'Change is made with the team, not to it.',
        [
          'with the team',
          'buy-in',
          'collaborat',
          'pair',
          'stakeholder',
          'workshop',
          'consensus',
          'involve',
        ],
        'How do you make sure the team owns what you change?',
        { w: 2 },
      ),
      concept(
        'sustainable-plan',
        'A plan with measures',
        'Defined outcomes and a way to tell whether they are being met.',
        ['roadmap', 'plan', 'goals', 'okr', 'success', 'measure', 'targets', '30', '60', '90'],
        'How would you know at day ninety whether it was working?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'fin-reliability-vs-velocity',
    rounds: ['final'],
    topic: 'sre',
    technologies: ['sre'],
    difficulty: 'staff',
    prompt:
      'Product wants to ship faster; reliability is slipping. How do you handle the tension between velocity and stability?',
    intent:
      'A staff-level judgment question: shared language, error budgets and context-sensitive decisions.',
    expectedSignals: ['tradeoff', 'metric', 'ownership'],
    wordRange: [90, 340],
    concepts: [
      concept(
        'shared-metric',
        'A shared, objective measure',
        'SLOs and error budgets turn an argument into a shared decision.',
        ['slo', 'error budget', 'budget', 'measure', 'objective', 'shared', 'data'],
        'How do you stop this being an argument of opinions?',
        { w: 3 },
      ),
      concept(
        'speed-enables',
        'Reliability work that increases speed',
        'Automation, better tests and safer deploys let teams ship faster safely.',
        [
          'faster safely',
          'automation',
          'safer deploy',
          'test',
          'feature flag',
          'canary',
          'ci',
          'reduce risk of',
        ],
        'Is there a way to get both rather than choosing?',
        { w: 3, kind: 'tradeoff' },
      ),
      concept(
        'context-decision',
        'Context-dependent trade-off',
        'The right balance depends on the product, the customers and the cost of failure.',
        [
          'depends',
          'context',
          'criticality',
          'customer',
          'cost of failure',
          'tier',
          'risk appetite',
          'business',
        ],
        'Would the answer be the same for a payments system and an internal tool?',
        { w: 2, kind: 'tradeoff' },
      ),
      concept(
        'policy-escalation',
        'An explicit policy when the budget is gone',
        'An agreed policy for slowing releases when reliability budgets are exhausted.',
        ['policy', 'freeze', 'agreement', 'escalat', 'leadership', 'agreed', 'pause'],
        'What happens when the budget is spent and a release is due?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'fin-build-vs-buy',
    rounds: ['final', 'architecture'],
    topic: 'architecture',
    technologies: [],
    difficulty: 'staff',
    prompt:
      'How do you decide whether to build an internal platform capability or adopt a managed service or open-source tool?',
    intent: 'Total cost of ownership thinking, lock-in, team capacity and exit strategy.',
    expectedSignals: ['tradeoff', 'cost', 'requirements'],
    wordRange: [90, 340],
    concepts: [
      concept(
        'tco',
        'Total cost of ownership',
        'Include running, upgrading, on-call and opportunity cost, not only licence price.',
        [
          'tco',
          'total cost',
          'maintenance',
          'on-call',
          'operat',
          'opportunity cost',
          'upgrade',
          'headcount',
          'hidden cost',
        ],
        'What costs are people most likely to forget?',
        { w: 3 },
      ),
      concept(
        'differentiation',
        'Build what differentiates',
        'Build where it is core to the business; buy commodity.',
        ['differentiat', 'core', 'commodity', 'competitive', 'unique', 'strategic', 'non-core'],
        'What makes something worth building yourselves?',
        { w: 3 },
      ),
      concept(
        'lock-in-exit',
        'Lock-in and exit',
        'Portability, data export and contract terms limit regret.',
        [
          'lock-in',
          'lock in',
          'vendor',
          'exit',
          'portab',
          'migration',
          'open standard',
          'switching cost',
        ],
        'How do you limit how stuck you are with the choice?',
        { w: 2, kind: 'tradeoff' },
      ),
      concept(
        'team-capacity',
        'Team capability and capacity',
        'A small team may not be able to run and secure a complex system.',
        ['capacity', 'skills', 'team size', 'expertise', 'bandwidth', 'staffing', 'small team'],
        'Does the size of your team change the answer?',
        { w: 2 },
      ),
      concept(
        'evaluate-reversible',
        'Evaluate with a reversible step',
        'A proof of concept or time-boxed pilot with clear criteria.',
        [
          'poc',
          'proof of concept',
          'pilot',
          'time-box',
          'timebox',
          'criteria',
          'evaluate',
          'trial',
          'reversible',
        ],
        'How do you test the decision before committing?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'fin-regret',
    rounds: ['final'],
    topic: 'behavioral',
    technologies: [],
    difficulty: 'senior',
    prompt: 'Which technical decision from your career would you make differently today, and why?',
    intent: 'Tests reflection, learning and judgment; a story with no regret is itself a signal.',
    expectedSignals: ['reflection', 'tradeoff', 'ownership', 'example'],
    wordRange: [80, 300],
    concepts: [
      concept(
        'specific-decision',
        'A specific decision with context',
        'A real decision, what was known at the time, and the alternatives considered.',
        [
          'at the time',
          'we chose',
          'i chose',
          'alternatives',
          'options',
          'decided',
          'constraint',
          'deadline',
        ],
        'What was the decision, and what were your alternatives at the time?',
        { w: 3 },
      ),
      concept(
        'consequence',
        'What actually happened',
        'The real cost of the choice.',
        [
          'consequence',
          'cost us',
          'ended up',
          'turned out',
          'problem was',
          'debt',
          'outage',
          'migrat',
        ],
        'What did it end up costing?',
        { w: 3 },
      ),
      concept(
        'what-changed',
        'What they would do now',
        'The better choice, and the reasoning that would lead to it.',
        [
          'would now',
          'instead',
          'differently',
          'next time',
          'today i',
          'better approach',
          'would choose',
        ],
        'What would you do instead, and what would make you choose it?',
        { w: 3 },
      ),
      concept(
        'generalised-lesson',
        'A lesson that transfers',
        'A principle applied to later decisions.',
        [
          'lesson',
          'principle',
          'rule of thumb',
          'since then',
          'now i always',
          'learned',
          'habit',
          'framework',
        ],
        'Where have you applied what you learned since?',
        { w: 2 },
      ),
    ],
  }),
]
