import type { QuestionSpec } from '@opsforge/types'
import { concept, question, redFlag } from './author'

export const screeningQuestions: QuestionSpec[] = [
  question({
    id: 'scr-deploy-flow',
    rounds: ['screening'],
    topic: 'ci-cd',
    technologies: ['ci-cd', 'jenkins', 'github-actions', 'gitlab'],
    difficulty: 'basic',
    prompt:
      'Walk me through what happens between a developer merging a pull request and that change running in production at your current or most recent company.',
    intent:
      'Checks that the candidate has really owned a delivery path: build, artifact, promotion, release strategy, verification and rollback.',
    expectedSignals: ['structured', 'example', 'ownership'],
    concepts: [
      concept(
        'build-test',
        'Automated build and tests',
        'Every merge builds and tests automatically so broken changes are caught before release.',
        ['build', 'unit test', 'tests run', 'pipeline runs', 'ci runs', 'lint'],
        'What stops a broken change from getting past the merge?',
        { w: 3 },
      ),
      concept(
        'artifact',
        'Immutable, versioned artifact',
        'The same built artifact (image, package) is promoted between environments rather than rebuilt.',
        ['artifact', 'image', 'registry', 'ecr', 'docker hub', 'package', 'tagged', 'immutable'],
        'What exactly is it that moves from one environment to the next?',
        { w: 2 },
      ),
      concept(
        'promotion',
        'Environment promotion and approvals',
        'Changes move through staging with gates or approvals before production.',
        ['staging', 'promote', 'promotion', 'approval', 'approve', 'environments', 'qa env'],
        'Where does it run before real users see it, and who decides it can move on?',
      ),
      concept(
        'release-strategy',
        'Release strategy',
        'Rolling, canary or blue/green releases limit blast radius.',
        ['canary', 'blue/green', 'blue green', 'rolling', 'feature flag', 'progressive'],
        'How do you limit the damage if that release is bad?',
        { w: 3 },
      ),
      concept(
        'verify-rollback',
        'Verification and rollback',
        'Post-deploy health checks and a fast rollback path close the loop.',
        ['rollback', 'roll back', 'revert', 'health check', 'smoke test', 'monitor', 'verify'],
        'The deploy finishes. How do you know it is actually healthy, and what if it is not?',
        { w: 3 },
      ),
    ],
  }),
  question({
    id: 'scr-container-vs-vm',
    rounds: ['screening', 'technical'],
    topic: 'containers',
    technologies: ['docker', 'kubernetes', 'containers'],
    difficulty: 'basic',
    prompt:
      'Explain the difference between a container and a virtual machine, and tell me when you would still choose a VM.',
    intent: 'A fundamentals check. Weak candidates call containers "lightweight VMs".',
    concepts: [
      concept(
        'shared-kernel',
        'Containers share the host kernel',
        'Containers are isolated processes using namespaces and cgroups on the host kernel; a VM runs its own kernel.',
        [
          'share the host kernel',
          'same kernel',
          'shared kernel',
          'host kernel',
          'namespace',
          'cgroup',
        ],
        'What does a container actually share with the machine it runs on?',
        { w: 3 },
      ),
      concept(
        'hypervisor',
        'VMs virtualise hardware',
        'A hypervisor presents virtual hardware, and each VM boots a full guest OS.',
        [
          'hypervisor',
          'guest os',
          'full os',
          'virtual hardware',
          'own kernel',
          'own operating system',
        ],
        'What is each virtual machine carrying that a container is not?',
        { w: 2 },
      ),
      concept(
        'overhead',
        'Startup and density',
        'Containers start in seconds and pack more densely because there is no guest OS.',
        ['start faster', 'startup', 'boot', 'density', 'overhead', 'footprint', 'seconds'],
        'What is the practical effect of that on startup time and how many you can run per host?',
      ),
      concept(
        'isolation-limits',
        'Isolation strength differs',
        'A VM boundary is stronger than a container boundary, which matters for untrusted or multi-tenant workloads.',
        [
          'stronger isolation',
          'isolation',
          'security boundary',
          'multi-tenant',
          'untrusted',
          'escape',
        ],
        'Which of the two would you trust more with workloads from different customers, and why?',
        { w: 2, kind: 'tradeoff' },
      ),
      concept(
        'vm-cases',
        'When a VM is the right tool',
        'Different kernel or OS, strong tenant isolation, legacy or stateful software, compliance boundaries.',
        ['windows', 'different kernel', 'legacy', 'kernel module', 'compliance', 'stateful'],
        'Give me a concrete case where you would pick a VM even with a container platform available.',
        { w: 2, kind: 'tradeoff' },
      ),
    ],
    redFlags: [
      redFlag(
        'lightweight-vm',
        'Containers are "lightweight VMs"',
        ['lightweight vm', 'light weight vm', 'mini vm', 'small vm', 'tiny vm', 'like a vm but'],
        'Does a container boot its own operating system? Walk me through what is actually running.',
        'Describing a container as a small VM misses that it is a process on the host kernel.',
      ),
    ],
  }),
  question({
    id: 'scr-secrets',
    rounds: ['screening', 'technical'],
    topic: 'security',
    technologies: ['vault', 'kubernetes', 'aws', 'ci-cd'],
    difficulty: 'intermediate',
    prompt: 'How do you handle secrets in a CI/CD pipeline and in running workloads?',
    intent:
      'Looks for a coherent model: never in git, a real secret store, short-lived identity-based access, rotation and detection.',
    expectedSignals: ['example', 'security'],
    concepts: [
      concept(
        'not-in-git',
        'Secrets never live in source control',
        'Credentials in repos or images are exposed to everyone with access and persist in history.',
        [
          'never commit',
          'not in git',
          'not in the repo',
          'source control',
          'git history',
          'hard-coded',
          'hardcoded',
        ],
        'Where must a secret never be stored, and what makes that mistake so hard to undo?',
        { w: 2 },
      ),
      concept(
        'secret-store',
        'A dedicated secret manager',
        'Vault, AWS Secrets Manager or SSM Parameter Store hold secrets with access control and audit.',
        [
          'vault',
          'secrets manager',
          'parameter store',
          'ssm',
          'key vault',
          'external secrets',
          'sealed secrets',
          'sops',
        ],
        'Where do the secrets live instead, and how does the workload obtain them?',
        { w: 3 },
      ),
      concept(
        'short-lived',
        'Short-lived, identity-based credentials',
        'OIDC federation, IRSA or workload identity replace long-lived keys with tokens that expire.',
        [
          'oidc',
          'irsa',
          'workload identity',
          'short-lived',
          'short lived',
          'temporary credentials',
          'assume role',
          'sts',
          'federat',
        ],
        'Can the pipeline or pod authenticate without holding any long-lived key at all?',
        {
          w: 3,
          depth:
            'You mentioned avoiding static credentials. How does the token get issued and what stops it being reused elsewhere?',
        },
      ),
      concept(
        'rotation',
        'Rotation and revocation',
        'Secrets must be rotatable without downtime, and revocable when leaked.',
        ['rotat', 'revoke', 'expire', 'lease', 'ttl'],
        'A secret leaks tonight. How quickly and how safely can you change it?',
      ),
      concept(
        'detection',
        'Scanning for leaks',
        'Pre-commit and CI secret scanning catch mistakes early.',
        ['gitleaks', 'trufflehog', 'secret scanning', 'scan', 'pre-commit', 'detect'],
        'How would you find out that someone committed one anyway?',
        { w: 1 },
      ),
    ],
    redFlags: [
      redFlag(
        'base64-is-encryption',
        'Treating base64 as protection',
        [
          'base64 encoded so',
          'base64 is secure',
          'base64 encrypt',
          'encoded in base64 so it',
          'base64 which is secure',
        ],
        'Is base64 encoding a security control? What would someone with read access to that object see?',
        'Kubernetes Secrets are only base64 encoded. Encryption at rest and tight RBAC provide the protection.',
      ),
    ],
  }),
  question({
    id: 'scr-on-call',
    rounds: ['screening', 'behavioral'],
    topic: 'sre',
    technologies: ['sre', 'on-call', 'pagerduty'],
    difficulty: 'intermediate',
    prompt:
      'Tell me about your on-call experience. What does a good rotation look like, and what made yours healthy or painful?',
    intent:
      'Probes operational maturity: alert quality, runbooks, sustainability and learning from pages.',
    expectedSignals: ['example', 'reflection', 'ownership'],
    wordRange: [70, 260],
    concepts: [
      concept(
        'actionable-alerts',
        'Alerts are actionable',
        'Pages should be urgent, user-impacting and need a human; everything else is a ticket.',
        [
          'actionable',
          'alert fatigue',
          'noisy',
          'noise',
          'false positive',
          'symptom',
          'page only',
          'urgent',
        ],
        'What decides whether something pages a person at 3am or waits until morning?',
        { w: 3 },
      ),
      concept(
        'runbooks',
        'Runbooks and ownership',
        'Each alert links to a runbook and has a clear owner.',
        ['runbook', 'playbook', 'documentation', 'owner', 'ownership'],
        'When someone new gets paged for a service they do not know, what do they have to work with?',
      ),
      concept(
        'escalation',
        'Escalation and handoff',
        'A clear escalation path and a handoff routine prevent heroics and lost context.',
        [
          'escalat',
          'handoff',
          'hand off',
          'secondary',
          'backup',
          'follow the sun',
          'incident commander',
        ],
        'What happens when the person on call is stuck or needs help?',
      ),
      concept(
        'sustainability',
        'Sustainable load',
        'Rotation size, fair compensation and a page budget keep on-call livable.',
        [
          'rotation',
          'compensat',
          'time off',
          'burnout',
          'toil',
          'pages per',
          'page budget',
          'fair',
        ],
        'How do you keep it sustainable for the people doing it?',
      ),
      concept(
        'learning-loop',
        'Learning from pages',
        'Postmortems and recurring-page reviews turn pages into fixes.',
        [
          'postmortem',
          'post-mortem',
          'retro',
          'review',
          'root cause',
          'eliminate',
          'follow-up',
          'reduce toil',
        ],
        'What did you do so the same page did not wake you again?',
        { w: 3 },
      ),
    ],
  }),
  question({
    id: 'scr-iac',
    rounds: ['screening', 'technical'],
    topic: 'terraform',
    technologies: ['terraform', 'ansible', 'cloudformation', 'pulumi'],
    difficulty: 'basic',
    prompt:
      'What is infrastructure as code, and what problems did it actually solve for your team in practice?',
    intent: 'Separates people who have run IaC at scale from those who recite the definition.',
    expectedSignals: ['example', 'tradeoff'],
    concepts: [
      concept(
        'versioned-reviewed',
        'Versioned and reviewed',
        'Infrastructure changes go through version control and code review like application code.',
        ['version control', 'git', 'pull request', 'code review', 'peer review', 'audit'],
        'How does a change to infrastructure get reviewed and tracked?',
        { w: 3 },
      ),
      concept(
        'repeatable',
        'Repeatable environments',
        'The same definition produces consistent environments and cuts snowflake servers.',
        [
          'repeatable',
          'reproducible',
          'consistent',
          'snowflake',
          'parity',
          'identical',
          'recreate',
        ],
        'If you lost an environment tonight, how would you rebuild it?',
        { w: 3 },
      ),
      concept(
        'drift',
        'Drift detection',
        'Comparing declared and real state reveals out-of-band changes.',
        ['drift', 'out of band', 'manual change', 'console change', 'plan shows', 'reconcile'],
        'What happens when someone changes a resource by hand in the console?',
      ),
      concept(
        'idempotent-state',
        'Declarative and idempotent',
        'Declarative tools converge to the desired state and are safe to re-run, usually by tracking state.',
        ['declarative', 'idempotent', 'desired state', 'state file', 'converge'],
        'What makes it safe to run the same code twice?',
      ),
      concept(
        'iac-costs',
        'Costs and pitfalls',
        'State management, module sprawl, blast radius and the learning curve are real costs.',
        [
          'state management',
          'blast radius',
          'module',
          'learning curve',
          'complexity',
          'downside',
          'overhead',
        ],
        'What has been the hardest part of living with it?',
        { w: 2, kind: 'tradeoff' },
      ),
    ],
  }),
]
