import type { QuestionSpec } from '@opsforge/types'
import { concept, question, redFlag } from './author'

export const technicalQuestions: QuestionSpec[] = [
  question({
    id: 'tech-k8s-probes',
    rounds: ['technical'],
    topic: 'kubernetes',
    technologies: ['kubernetes'],
    difficulty: 'senior',
    prompt:
      'Explain liveness, readiness and startup probes in Kubernetes. What goes wrong when they are configured badly?',
    intent:
      'Tests whether the candidate understands probes as traffic and restart controls, and knows the failure modes.',
    expectedSignals: ['example', 'tradeoff'],
    concepts: [
      concept(
        'readiness-traffic',
        'Readiness gates traffic',
        'A failing readiness probe removes the pod from Service endpoints; the container is not restarted.',
        [
          'readiness',
          'removed from the service',
          'removed from endpoints',
          'load balancer',
          'receive traffic',
          'endpoints',
        ],
        'How does Kubernetes decide whether a pod should receive traffic right now?',
        { w: 3 },
      ),
      concept(
        'liveness-restart',
        'Liveness restarts the container',
        'A failing liveness probe makes the kubelet kill and restart the container; it detects deadlock, not slowness.',
        ['liveness', 'kubelet', 'restart', 'deadlock', 'kill the container'],
        'And how does it decide that a container is dead and needs replacing?',
        { w: 3 },
      ),
      concept(
        'startup-probe',
        'Startup probes protect slow starters',
        'A startup probe holds off liveness checks until a slow application has booted.',
        [
          'startup probe',
          'slow start',
          'slow to start',
          'initialdelay',
          'initial delay',
          'boot time',
        ],
        'What about an application that takes two minutes to warm up?',
        { w: 2 },
      ),
      concept(
        'probe-cascade',
        'Bad probes cause cascading failure',
        'A liveness probe that checks a shared dependency can restart every pod when that dependency is down.',
        [
          'cascad',
          'restart loop',
          'all pods',
          'dependency',
          'database check',
          'thundering',
          'crashloop',
        ],
        'Describe a probe configuration that would turn a small outage into a big one.',
        { w: 3, kind: 'tradeoff' },
      ),
      concept(
        'probe-tuning',
        'Timing parameters',
        'periodSeconds, timeoutSeconds and failureThreshold decide how quickly and how safely a pod is judged unhealthy.',
        ['timeoutseconds', 'failurethreshold', 'periodseconds', 'threshold', 'timeout', 'period'],
        'What would you tune so a brief GC pause does not get a pod killed?',
        { w: 1 },
      ),
    ],
    redFlags: [
      redFlag(
        'readiness-restarts',
        'Readiness restarts the container',
        [
          'readiness probe restarts',
          'readiness restarts',
          'readiness probe kills',
          'readiness will restart',
          'readiness probe fails the container is restarted',
        ],
        'Are you sure the readiness probe restarts anything? What does it change instead?',
        'A failing readiness probe only removes the pod from endpoints. Restarts come from the liveness probe.',
      ),
    ],
  }),
  question({
    id: 'tech-terraform-state',
    rounds: ['technical'],
    topic: 'terraform',
    technologies: ['terraform'],
    difficulty: 'senior',
    prompt: 'How does Terraform state work, and how do you run it safely with a team?',
    intent:
      'Checks real-world Terraform experience: remote state, locking, secrets in state, blast radius.',
    expectedSignals: ['tradeoff', 'example'],
    concepts: [
      concept(
        'state-mapping',
        'State maps code to real resources',
        'State records which real resource each block manages so plan can diff desired against actual.',
        [
          'state maps',
          'maps to',
          'mapping',
          'tracks',
          'resource ids',
          'source of truth',
          'plan compares',
          'diff',
        ],
        'How does Terraform know which real resource a block of code refers to?',
        { w: 3 },
      ),
      concept(
        'remote-backend',
        'Remote state backend',
        'Shared state lives in a remote backend (S3, GCS, Terraform Cloud), never on a laptop.',
        ['remote state', 'remote backend', 's3 bucket', 'backend', 'terraform cloud', 'gcs'],
        'Where does that state live when five engineers work on the same stack?',
        { w: 3 },
      ),
      concept(
        'state-locking',
        'State locking',
        'A lock (DynamoDB table, native lockfile) stops two applies corrupting state.',
        ['lock', 'dynamodb', 'concurrent', 'two applies', 'at the same time'],
        'What stops two people running apply at the same moment?',
        { w: 3 },
      ),
      concept(
        'sensitive-state',
        'State contains secrets',
        'State can hold plaintext secrets, so it must be encrypted and access-controlled.',
        ['sensitive', 'secrets in state', 'plaintext', 'encrypt', 'access to the state', 'kms'],
        'Is there anything in that state file you would not want everyone to read?',
        { w: 2 },
      ),
      concept(
        'drift-refresh',
        'Drift and refresh',
        'Plan refreshes against reality and surfaces manual changes.',
        ['drift', 'refresh', 'manual change', 'out of band', 'import'],
        'Someone resized an instance in the console. What does the next plan do?',
      ),
      concept(
        'state-blast-radius',
        'Splitting state to limit blast radius',
        'Per-environment and per-component state keeps a mistake or a corrupt file from affecting everything.',
        [
          'split',
          'separate state',
          'per environment',
          'workspace',
          'blast radius',
          'small state',
          'module',
        ],
        'How do you decide how much infrastructure goes into one state?',
        { w: 2, kind: 'tradeoff' },
      ),
    ],
    redFlags: [
      redFlag(
        'state-in-git',
        'State committed to git',
        [
          'commit the state',
          'state in git',
          'state file in git',
          'checked into git',
          'store the state in the repo',
          'state in the repo',
        ],
        'What are the risks of keeping the state file in the repository?',
        'State holds secrets and has no locking in git. Use a remote backend with locking and encryption.',
      ),
    ],
  }),
  question({
    id: 'tech-cicd-security',
    rounds: ['technical'],
    topic: 'security',
    technologies: ['ci-cd', 'github-actions', 'jenkins', 'docker'],
    difficulty: 'senior',
    prompt: 'How would you secure a CI/CD pipeline against supply-chain attacks?',
    intent: 'Looks for layered controls across source, build, dependencies, artifacts and deploy.',
    expectedSignals: ['security', 'tradeoff', 'structured'],
    concepts: [
      concept(
        'pin-dependencies',
        'Pin dependencies and actions',
        'Lockfiles, digest-pinned images and pinned third-party actions stop silent upstream changes.',
        ['pin', 'lockfile', 'lock file', 'digest', 'sha', 'version lock', 'dependabot', 'renovate'],
        'An upstream package or action gets compromised. How do you avoid pulling it automatically?',
        { w: 3 },
      ),
      concept(
        'sign-attest',
        'Sign artifacts and keep provenance',
        'Signing (cosign), SBOMs and provenance attestations let the deploy step trust only what the pipeline built.',
        ['sign', 'cosign', 'sigstore', 'sbom', 'provenance', 'slsa', 'attestation', 'notary'],
        'How does the cluster know an image really came from your pipeline?',
        { w: 3 },
      ),
      concept(
        'runner-isolation',
        'Isolated, least-privilege runners',
        'Ephemeral runners with scoped credentials limit what a compromised job can reach.',
        [
          'ephemeral',
          'isolated runner',
          'least privilege',
          'self-hosted runner',
          'sandbox',
          'scoped token',
          'permissions',
        ],
        'If a build job is compromised, what can it reach?',
        { w: 3 },
      ),
      concept(
        'oidc-credentials',
        'No long-lived deploy credentials',
        'OIDC federation gives jobs short-lived cloud credentials instead of stored keys.',
        ['oidc', 'short-lived', 'federat', 'no static', 'temporary credentials'],
        'How does the pipeline authenticate to the cloud?',
        { w: 2 },
      ),
      concept(
        'scanning',
        'Layered scanning',
        'SAST, dependency (SCA), secret and container scanning catch different classes of problem.',
        [
          'sast',
          'sca',
          'trivy',
          'snyk',
          'scan',
          'dependency check',
          'container scan',
          'secret scan',
        ],
        'What automated checks run before something can ship?',
        { w: 2 },
      ),
      concept(
        'branch-protection',
        'Protected branches and review',
        'Required reviews and protected branches stop one person pushing straight to production.',
        [
          'branch protection',
          'protected branch',
          'code review',
          'required review',
          'two-person',
          'codeowners',
          'approval',
        ],
        'What stops a single person shipping a malicious change?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'tech-linux-load',
    rounds: ['technical', 'troubleshooting'],
    topic: 'linux',
    technologies: ['linux'],
    difficulty: 'senior',
    prompt:
      'A Linux server shows a load average of 40 on 8 cores, but CPU utilisation looks low. What is going on and how do you find out?',
    intent:
      'Tests understanding that load average counts uninterruptible I/O waiters, and a sound diagnostic order.',
    expectedSignals: ['hypothesis', 'structured'],
    concepts: [
      concept(
        'load-definition',
        'Load counts runnable and uninterruptible tasks',
        'Load average includes processes in D state waiting on I/O, so it can be high with idle CPUs.',
        [
          'uninterruptible',
          'd state',
          'blocked on i/o',
          'waiting on i/o',
          'runnable',
          'iowait',
          'io wait',
        ],
        'What exactly does the load average count?',
        { w: 3 },
      ),
      concept(
        'io-saturation',
        'Disk or network filesystem saturation',
        'A saturated disk or a hung NFS mount leaves many tasks blocked.',
        ['iostat', 'disk', 'nfs', 'saturat', 'storage', 'await', 'utilization', 'ebs'],
        'If the CPUs are idle, what are all those processes waiting for?',
        { w: 3 },
      ),
      concept(
        'tooling',
        'Concrete diagnostic tools',
        'vmstat, iostat, pidstat, top/ps in D state and dmesg narrow it down quickly.',
        ['vmstat', 'iostat', 'pidstat', 'top', 'ps aux', 'dmesg', 'sar', 'iotop'],
        'Which commands would you run, and in what order?',
        { w: 2 },
      ),
      concept(
        'memory-pressure',
        'Memory pressure and swapping',
        'Heavy swapping blocks tasks on I/O and inflates load.',
        ['swap', 'memory pressure', 'oom', 'page cache', 'thrash', 'free -m'],
        'Could memory be involved, and how would you tell?',
        { w: 2 },
      ),
      concept(
        'find-offender',
        'Identify the offending process',
        'Find which processes are in D state and what they are touching.',
        ['d state', 'process in d', 'lsof', 'strace', 'which process', 'offending'],
        'Once you know it is I/O, how do you find who is causing it?',
        { w: 1 },
      ),
    ],
    redFlags: [
      redFlag(
        'load-is-cpu',
        'Load average is CPU usage',
        [
          'load average is the cpu',
          'load is cpu usage',
          'load average is cpu',
          'load average means cpu',
          'load is the cpu',
        ],
        'If load were just CPU usage, why would the CPUs be idle here?',
        'Load average is a count of runnable plus uninterruptible tasks, not a CPU percentage.',
      ),
    ],
  }),
  question({
    id: 'tech-slo-error-budget',
    rounds: ['technical', 'final'],
    topic: 'sre',
    technologies: ['sre', 'prometheus'],
    difficulty: 'senior',
    prompt: 'What is an SLO, how does it differ from an SLA, and how do you use an error budget?',
    intent:
      'Checks for practical SRE practice, not definitions: choosing SLIs, budget math and the policy that follows.',
    expectedSignals: ['tradeoff', 'example', 'metric'],
    concepts: [
      concept(
        'sli-slo-sla',
        'SLI, SLO and SLA',
        'An SLI is a measurement, an SLO the internal target for it, and an SLA the contractual promise with consequences.',
        ['sli', 'indicator', 'target', 'contract', 'penalt', 'sla'],
        'How do the measurement, the target and the contract relate to each other?',
        { w: 2 },
      ),
      concept(
        'error-budget-math',
        'Error budget arithmetic',
        'The budget is 100% minus the SLO; 99.9% allows about 43 minutes of failure a month.',
        ['error budget', '100%', '43 minutes', 'allowed downtime', 'budget remaining', 'burn'],
        'For a 99.9% target, how much failure are you allowed, and what does that mean day to day?',
        { w: 3 },
      ),
      concept(
        'budget-policy',
        'A policy tied to the budget',
        'When the budget is spent, risky releases slow and reliability work takes priority.',
        [
          'freeze',
          'policy',
          'slow down releases',
          'prioriti',
          'stop shipping',
          'reliability work',
          'feature work',
        ],
        'What actually changes when the budget runs out?',
        { w: 3 },
      ),
      concept(
        'user-centric-sli',
        'SLIs from user journeys',
        'Good SLIs measure what users experience (availability, latency of a journey) rather than CPU.',
        [
          'user journey',
          'user-facing',
          'user experience',
          'availability',
          'latency',
          'request success',
          'critical journey',
        ],
        'How do you pick what to measure for a checkout service?',
        { w: 2 },
      ),
      concept(
        'burn-rate',
        'Burn-rate alerting',
        'Multi-window burn-rate alerts page on fast budget consumption and ticket on slow burn.',
        ['burn rate', 'burn-rate', 'multi-window', 'fast burn', 'slow burn'],
        'How would you alert on the SLO without paging on every blip?',
        { w: 2 },
      ),
      concept(
        'not-100',
        'Why not 100%',
        'Perfect reliability is unreachable and expensive; the target should match user need and cost.',
        [
          'not 100',
          'cost of reliability',
          'diminishing',
          'too expensive',
          'users cannot tell',
          'velocity',
        ],
        'Why not just aim for 100%?',
        { w: 2, kind: 'tradeoff' },
      ),
    ],
  }),
  question({
    id: 'tech-container-image',
    rounds: ['technical'],
    topic: 'containers',
    technologies: ['docker', 'containers'],
    difficulty: 'intermediate',
    prompt: 'How do you make a container image small, fast to build and safe to run?',
    intent: 'Practical Docker hygiene across build, size, caching and runtime security.',
    expectedSignals: ['structured', 'security'],
    concepts: [
      concept(
        'multi-stage',
        'Multi-stage builds',
        'Build in one stage and copy only the artifact into a minimal runtime stage.',
        ['multi-stage', 'multi stage', 'build stage', 'copy --from', 'builder'],
        'How do you keep compilers and build tools out of the final image?',
        { w: 3 },
      ),
      concept(
        'minimal-base',
        'Minimal base image',
        'Slim, distroless or scratch bases shrink size and attack surface.',
        ['distroless', 'alpine', 'slim', 'scratch', 'minimal base', 'small base'],
        'What do you start from, and what does that choice cost you?',
        { w: 2, kind: 'tradeoff' },
      ),
      concept(
        'layer-cache',
        'Layer ordering and caching',
        'Order instructions from least to most frequently changed so layers are cached.',
        ['layer', 'cache', 'order of', 'dependencies first', 'copy package', 'buildkit'],
        'A one-line code change rebuilds everything. Why, and what do you change?',
        { w: 3 },
      ),
      concept(
        'non-root',
        'Run as non-root',
        'A non-root user, read-only filesystem and dropped capabilities limit what a compromised container can do.',
        [
          'non-root',
          'nonroot',
          'user 1000',
          'read-only',
          'drop capabilities',
          'capabilit',
          'privileged',
        ],
        'If someone breaks into the process, what are they running as?',
        { w: 3 },
      ),
      concept(
        'no-secrets-in-layers',
        'No secrets baked into layers',
        'Anything copied into a layer persists in the image, even if deleted later.',
        ['secret', 'build arg', 'buildkit secret', 'layer history', 'credential', 'dockerignore'],
        'How do you make sure a token used during the build does not ship in the image?',
        { w: 2 },
      ),
      concept(
        'scan-pin',
        'Scan and pin',
        'Pin base image digests and scan images in CI for known vulnerabilities.',
        ['trivy', 'scan', 'grype', 'pin', 'digest', 'vulnerabilit', 'cve'],
        'How do you keep known vulnerabilities from reaching production?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'tech-aws-iam',
    rounds: ['technical'],
    topic: 'aws',
    technologies: ['aws', 'iam'],
    difficulty: 'senior',
    prompt:
      'Explain how IAM roles and policies work in AWS, and how you apply least privilege in practice.',
    intent:
      'Policy evaluation logic, temporary credentials and a realistic least-privilege process.',
    expectedSignals: ['security', 'example'],
    concepts: [
      concept(
        'roles-temporary',
        'Roles issue temporary credentials',
        'Assuming a role returns short-lived credentials via STS, so workloads need no stored keys.',
        [
          'assume role',
          'assumerole',
          'sts',
          'temporary credentials',
          'short-lived',
          'instance profile',
          'irsa',
        ],
        'How does a workload get credentials without a stored access key?',
        { w: 3 },
      ),
      concept(
        'policy-evaluation',
        'Policy evaluation logic',
        'Default deny; an explicit deny always wins; permissions are the intersection of identity policy, boundaries and SCPs.',
        [
          'explicit deny',
          'default deny',
          'implicit deny',
          'scp',
          'permission boundary',
          'resource policy',
          'evaluation',
        ],
        'Two policies conflict. How does AWS decide whether the request is allowed?',
        { w: 3 },
      ),
      concept(
        'cross-account',
        'Cross-account access',
        'A role trust policy in the target account plus a permission in the caller allow cross-account assume.',
        ['trust policy', 'cross-account', 'cross account', 'principal', 'another account'],
        'A service in account A needs a bucket in account B. What has to be true in each account?',
        { w: 2 },
      ),
      concept(
        'least-priv-process',
        'A practical least-privilege process',
        'Start narrow, use Access Analyzer and CloudTrail activity to trim, scope by resource and condition.',
        [
          'access analyzer',
          'cloudtrail',
          'last used',
          'conditions',
          'scope down',
          'iterate',
          'narrow',
        ],
        'You inherit a role with admin rights. How do you get it to least privilege without breaking things?',
        { w: 3 },
      ),
      concept(
        'workload-identity',
        'Workload identity for containers',
        'IRSA or Pod Identity binds IAM roles to service accounts instead of node-wide permissions.',
        ['irsa', 'pod identity', 'service account', 'oidc', 'node role'],
        'How do you give one pod access to one bucket and nothing else?',
        { w: 2 },
      ),
    ],
    redFlags: [
      redFlag(
        'static-keys',
        'Long-lived access keys for workloads',
        [
          'long-lived access keys for',
          'hardcode the access key',
          'put the access key in',
          'access keys in the app',
          'store the access key in the',
        ],
        'What happens when that key leaks, and how would you notice?',
        'Long-lived keys in applications are the most common cause of cloud credential leaks. Use roles and short-lived credentials.',
      ),
    ],
  }),
  question({
    id: 'tech-gitops',
    rounds: ['technical'],
    topic: 'gitops',
    technologies: ['argocd', 'flux', 'kubernetes', 'helm'],
    difficulty: 'senior',
    prompt:
      'What is GitOps, and how does it differ from push-based CI/CD? When would you not use it?',
    intent: 'Pull-based reconciliation, drift handling and an honest view of where GitOps hurts.',
    expectedSignals: ['tradeoff', 'example'],
    concepts: [
      concept(
        'desired-state-git',
        'Git holds the desired state',
        'The declared state of the system lives in git; changes are commits.',
        ['source of truth', 'desired state', 'declarative', 'git is', 'single source'],
        'Where is the truth about what should be running?',
        { w: 3 },
      ),
      concept(
        'pull-reconcile',
        'Pull-based reconciliation',
        'An in-cluster agent (Argo CD, Flux) continuously pulls and reconciles, so CI needs no cluster credentials.',
        ['argo', 'flux', 'reconcil', 'pull', 'in-cluster', 'agent', 'operator'],
        'What actually applies the change to the cluster, and who initiates it?',
        { w: 3 },
      ),
      concept(
        'drift-heal',
        'Drift detection and self-heal',
        'Out-of-band changes are detected and reverted to the declared state.',
        ['drift', 'self-heal', 'self heal', 'out of sync', 'revert manual', 'sync status'],
        'Someone edits a deployment with kubectl. What happens?',
        { w: 2 },
      ),
      concept(
        'audit-rollback',
        'Audit and rollback via git',
        'Every change is a reviewed commit, and rollback is a revert.',
        ['audit', 'history', 'git revert', 'rollback', 'pull request', 'review'],
        'How do you roll back, and how do you prove who changed what?',
        { w: 2 },
      ),
      concept(
        'gitops-secrets',
        'Secrets in a GitOps flow',
        'Secrets need sealed secrets, SOPS or an external secrets operator so plaintext never lands in git.',
        ['sealed secrets', 'sops', 'external secrets', 'vault', 'encrypted secret'],
        'How do secrets fit in if everything is in git?',
        { w: 2 },
      ),
      concept(
        'gitops-limits',
        'Where GitOps struggles',
        'Imperative steps, data migrations, promotion across environments and repo sprawl are awkward.',
        [
          'not suitable',
          'struggle',
          'migration',
          'imperative',
          'overhead',
          'promotion',
          'sprawl',
          'complexity',
          'downside',
        ],
        'Where has it hurt you, or where would you choose something else?',
        { w: 3, kind: 'tradeoff' },
      ),
    ],
  }),
  question({
    id: 'tech-https-request',
    rounds: ['technical', 'screening'],
    topic: 'networking',
    technologies: ['networking', 'dns', 'tls'],
    difficulty: 'intermediate',
    prompt:
      'What happens, in as much detail as you can give, when a user opens https://api.example.com in a browser?',
    intent: 'A classic that exposes how deep the candidate’s network model really is.',
    expectedSignals: ['structured'],
    wordRange: [80, 280],
    concepts: [
      concept(
        'dns',
        'DNS resolution',
        'The name is resolved through a recursive resolver and caches, honouring TTLs.',
        ['dns', 'resolver', 'recursive', 'ttl', 'a record', 'cname', 'authoritative'],
        'Before anything is sent, how does the browser find the address?',
        { w: 3 },
      ),
      concept(
        'tcp',
        'TCP connection',
        'A TCP three-way handshake (or QUIC) establishes the transport.',
        ['tcp', 'three-way', 'handshake', 'syn', 'quic', 'port 443'],
        'What has to be established before the first byte of HTTP?',
        { w: 2 },
      ),
      concept(
        'tls',
        'TLS handshake',
        'The server presents a certificate chain, the client validates it (and SNI picks the cert), keys are agreed.',
        ['tls', 'certificate', 'chain', 'sni', 'key exchange', 'ca ', 'trust store'],
        'How does the browser know it is talking to the real server?',
        { w: 3 },
      ),
      concept(
        'edge',
        'Load balancer or CDN edge',
        'The request usually hits a CDN or load balancer that terminates TLS and routes onwards.',
        ['load balancer', 'cdn', 'edge', 'ingress', 'reverse proxy', 'alb', 'nginx', 'terminat'],
        'What is the first thing of yours that the request reaches?',
        { w: 2 },
      ),
      concept(
        'debug-tools',
        'How to observe each step',
        'dig, curl -v and openssl s_client let you see each stage when something breaks.',
        ['dig', 'curl -v', 'openssl', 's_client', 'traceroute', 'tcpdump', 'nslookup'],
        'It fails. How do you tell which of those steps broke?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'tech-alerting',
    rounds: ['technical'],
    topic: 'observability',
    technologies: ['prometheus', 'grafana', 'alertmanager'],
    difficulty: 'senior',
    prompt: 'How do you design alerting so on-call is not flooded, but real incidents still page?',
    intent: 'Symptom-based alerting, routing, noise control and ownership.',
    expectedSignals: ['tradeoff', 'example', 'observability'],
    concepts: [
      concept(
        'symptom-based',
        'Alert on symptoms',
        'Page on user-visible symptoms (errors, latency) rather than every cause such as CPU.',
        [
          'symptom',
          'user-facing',
          'user impact',
          'golden signals',
          'cause-based',
          'customer impact',
        ],
        'What should be the trigger for a page, and what should not?',
        { w: 3 },
      ),
      concept(
        'severity-routing',
        'Severity and routing',
        'Urgent alerts page; the rest become tickets or dashboards, routed to the owning team.',
        ['severity', 'route', 'routing', 'ticket', 'page vs', 'warning', 'critical', 'team'],
        'How do you decide who is told, and how loudly?',
        { w: 2 },
      ),
      concept(
        'noise-control',
        'Noise control',
        'For-durations, grouping, deduplication and inhibition keep one failure from producing fifty pages.',
        ['for duration', 'for:', 'group', 'dedup', 'inhibit', 'silence', 'flap', 'alertmanager'],
        'One database failure fires fifty alerts. What do you do about that?',
        { w: 3 },
      ),
      concept(
        'burn-rate-slo',
        'SLO and burn-rate based paging',
        'Tie paging to SLO burn so the threshold reflects user pain.',
        ['burn rate', 'burn-rate', 'slo', 'error budget'],
        'How do you pick a threshold that is not arbitrary?',
        { w: 2 },
      ),
      concept(
        'runbook-owner',
        'Runbooks and ownership',
        'Every alert has an owner and a link to what to do.',
        ['runbook', 'owner', 'playbook', 'documentation', 'dashboard link'],
        'What does the person who gets paged have in front of them?',
        { w: 2 },
      ),
      concept(
        'alert-review',
        'Review and delete noisy alerts',
        'Alerts are reviewed regularly; those nobody acts on are removed or fixed.',
        ['review', 'prune', 'delete', 'remove alerts', 'audit alerts', 'noisy', 'retire'],
        'How do you keep the set healthy over time?',
        { w: 1 },
      ),
    ],
  }),
  question({
    id: 'tech-k8s-autoscaling',
    rounds: ['technical'],
    topic: 'kubernetes',
    technologies: ['kubernetes'],
    difficulty: 'senior',
    prompt: 'How does autoscaling work in Kubernetes, and what are the common traps?',
    intent: 'HPA mechanics, requests, node scaling and the traps that cause outages.',
    expectedSignals: ['tradeoff', 'scalability', 'example'],
    concepts: [
      concept(
        'hpa-mechanics',
        'HPA scales on a metric versus a target',
        'The HPA compares a metric (CPU utilisation of requests, or a custom metric) to a target and adjusts replicas.',
        [
          'hpa',
          'horizontal pod autoscaler',
          'target utilization',
          'desired replicas',
          'metrics server',
        ],
        'What does the horizontal autoscaler look at, and what does it change?',
        { w: 3 },
      ),
      concept(
        'requests-needed',
        'Resource requests drive utilisation scaling',
        'Utilisation is measured against requests, so missing or wrong requests make CPU scaling meaningless.',
        ['requests', 'resource request', 'cpu request', 'percentage of request'],
        'The HPA shows 400% utilisation on a deployment. What would that tell you?',
        { w: 3 },
      ),
      concept(
        'node-scaling',
        'Pods need nodes',
        'Cluster Autoscaler or Karpenter adds nodes for pending pods, which takes minutes.',
        [
          'cluster autoscaler',
          'karpenter',
          'pending pods',
          'node scaling',
          'new nodes',
          'node group',
        ],
        'The HPA wants more pods but there is no room. What happens next?',
        { w: 3 },
      ),
      concept(
        'stabilisation',
        'Flapping and stabilisation',
        'Stabilisation windows and scale-down policies stop thrashing.',
        ['stabiliz', 'stabilis', 'cooldown', 'flap', 'thrash', 'scale down policy', 'behavior'],
        'How do you stop it scaling up and down every few minutes?',
        { w: 2 },
      ),
      concept(
        'event-driven',
        'Scaling on the right signal',
        'Queue depth or request rate (KEDA, custom metrics) often beats CPU for async workloads.',
        ['keda', 'queue depth', 'custom metric', 'requests per second', 'lag', 'external metric'],
        'CPU is a poor signal for a queue consumer. What would you scale it on?',
        { w: 2, kind: 'tradeoff' },
      ),
      concept(
        'disruption-safety',
        'Protect availability while scaling',
        'PodDisruptionBudgets, graceful shutdown and surge settings keep scale-down from dropping traffic.',
        ['pdb', 'pod disruption budget', 'graceful', 'prestop', 'terminationgrace', 'surge'],
        'What keeps scale-down from dropping in-flight requests?',
        { w: 2 },
      ),
    ],
  }),
]
