import type { QuestionSpec } from '@opsforge/types'
import { concept, question, redFlag } from './author'

const TS_SIGNALS = ['scope-first', 'hypothesis', 'mitigation', 'verification'] as const

export const troubleshootingQuestions: QuestionSpec[] = [
  question({
    id: 'ts-crashloop',
    rounds: ['troubleshooting'],
    topic: 'kubernetes',
    technologies: ['kubernetes'],
    difficulty: 'senior',
    prompt:
      'A pod you just deployed is in CrashLoopBackOff. Walk me through exactly how you diagnose it, in the order you would do it.',
    intent:
      'Looks for an evidence-first order: events and status, previous logs, exit code, then config and resources.',
    expectedSignals: [...TS_SIGNALS],
    maxFollowUps: 3,
    concepts: [
      concept(
        'describe-events',
        'Read the pod status and events first',
        'kubectl describe shows the last state, exit code, restart reason and scheduling or probe events.',
        ['describe', 'events', 'last state', 'exit code', 'reason', 'kubectl get pod'],
        'Before changing anything, where do you look first to see what Kubernetes itself says happened?',
        { w: 3 },
      ),
      concept(
        'previous-logs',
        'Logs of the previous container',
        'The crashed container’s logs (kubectl logs --previous) usually show the failure.',
        ['logs', '--previous', 'previous container', 'previous logs', 'stack trace', 'stderr'],
        'The container restarts every few seconds. How do you see why the last one died?',
        { w: 3 },
      ),
      concept(
        'exit-reason',
        'Distinguish OOMKilled, config error and probe failure',
        'Exit code 137/OOMKilled, exit 1 and liveness restarts point to different causes.',
        [
          'oomkilled',
          'oom',
          '137',
          'exit code 1',
          'liveness',
          'probe',
          'memory limit',
          'exit status',
        ],
        'What are the different reasons a container can keep dying, and how would you tell them apart?',
        { w: 3 },
      ),
      concept(
        'config-deps',
        'Check config, secrets and dependencies',
        'A missing env var, bad ConfigMap or Secret, or an unreachable dependency is a common cause.',
        [
          'configmap',
          'secret',
          'env var',
          'environment variable',
          'config',
          'dependency',
          'image',
          'imagepull',
        ],
        'It worked in staging. What would differ in this environment?',
        { w: 2 },
      ),
      concept(
        'recent-change',
        'Correlate with the last change and roll back',
        'Tie it to the last deploy, then roll back if it is user-impacting while investigating.',
        [
          'rollout undo',
          'roll back',
          'rollback',
          'last deploy',
          'recent change',
          'previous version',
          'what changed',
        ],
        'Production traffic depends on this. What do you do while you investigate?',
        { w: 2 },
      ),
      concept(
        'debug-tools',
        'Reproduce in a debuggable way',
        'kubectl debug, an overridden entrypoint, or running the image locally let you inspect a container that exits immediately.',
        [
          'kubectl debug',
          'ephemeral container',
          'override',
          'entrypoint',
          'sleep',
          'run locally',
          'exec',
        ],
        'The container exits before you can exec into it. What now?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'ts-502-after-deploy',
    rounds: ['troubleshooting'],
    topic: 'networking',
    technologies: ['kubernetes', 'nginx', 'aws', 'load-balancer'],
    difficulty: 'senior',
    prompt:
      'Right after a deploy, users report intermittent 502 errors. The pods all show Ready. How do you work out what is going on?',
    intent:
      'Tests layered reasoning: where in the request path, what changed, and the deploy-time races (draining, readiness, keep-alive).',
    expectedSignals: [...TS_SIGNALS],
    maxFollowUps: 3,
    concepts: [
      concept(
        'scope-impact',
        'Establish scope and impact first',
        'How many users, which endpoints, which backends, since when, and does it line up with the deploy?',
        [
          'scope',
          'how many',
          'which endpoint',
          'percentage',
          'dashboard',
          'error rate',
          'started',
          'timeline',
          'blast radius',
        ],
        'Before you theorise, what do you want to know about how widespread it is?',
        { w: 3 },
      ),
      concept(
        'request-path',
        'Walk the request path layer by layer',
        'CDN or load balancer, ingress, service, pod: find which hop returns the 502.',
        [
          'load balancer',
          'ingress',
          'alb',
          'proxy',
          'upstream',
          'access logs',
          'hop',
          'layer',
          'request path',
        ],
        'Where could the 502 originate, and how would you narrow it down?',
        { w: 3 },
      ),
      concept(
        'deploy-race',
        'Deploy-time races',
        'Pods receiving traffic before they are ready, or being killed without draining, cause 502s during rollouts.',
        [
          'draining',
          'graceful',
          'prestop',
          'termination',
          'connection draining',
          'rolling update',
          'readiness',
          'in-flight',
          'deregistration',
        ],
        'Why would a rollout in particular cause this?',
        { w: 3 },
      ),
      concept(
        'keepalive-mismatch',
        'Keep-alive and timeout mismatches',
        'A backend closing idle connections sooner than the proxy’s keep-alive causes sporadic 502s.',
        [
          'keep-alive',
          'keepalive',
          'idle timeout',
          'timeout mismatch',
          'connection reset',
          'upstream closed',
        ],
        'The same request succeeds when retried. What kind of cause fits that pattern?',
        { w: 2 },
      ),
      concept(
        'mitigate-rollback',
        'Mitigate before root cause',
        'If it correlates with the deploy, roll back or shift traffic, then investigate with the pressure off.',
        [
          'roll back',
          'rollback',
          'revert',
          'shift traffic',
          'canary',
          'mitigate',
          'stop the bleeding',
        ],
        'Customers are affected right now. What do you do about that before you know the cause?',
        { w: 3 },
      ),
      concept(
        'verify-fix',
        'Verify recovery and prevent recurrence',
        'Confirm error rate returns to baseline, then fix draining or readiness and add a deploy-time check.',
        [
          'verify',
          'error rate back',
          'baseline',
          'postmortem',
          'prevent',
          'alert',
          'add a test',
          'follow-up',
        ],
        'How do you know it is actually fixed, and how do you stop it happening on the next deploy?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'ts-latency-db',
    rounds: ['troubleshooting'],
    topic: 'observability',
    technologies: ['postgres', 'mysql', 'observability', 'prometheus'],
    difficulty: 'senior',
    prompt:
      'API p99 latency tripled over the last hour. Nothing was deployed. Where do you start, and how do you find the cause?',
    intent:
      'Looks for method over guesswork: compare to baseline, isolate by dimension, follow the dependency.',
    expectedSignals: [...TS_SIGNALS],
    maxFollowUps: 3,
    concepts: [
      concept(
        'baseline-compare',
        'Compare against a baseline and check changes',
        'Confirm it is real, when it began, and what changed even without a deploy (traffic, config, data, dependencies).',
        [
          'baseline',
          'compare',
          'when did it start',
          'change',
          'traffic',
          'timeline',
          'flag',
          'cron',
          'batch',
        ],
        'What would you want to compare the current numbers against?',
        { w: 3 },
      ),
      concept(
        'isolate-dimension',
        'Isolate by dimension',
        'Slice by endpoint, region, customer, instance or version to see whether it is global or narrow.',
        [
          'endpoint',
          'by region',
          'by instance',
          'slice',
          'breakdown',
          'group by',
          'one pod',
          'percentile',
          'which requests',
        ],
        'Is every request slow, or only some? How do you find out?',
        { w: 3 },
      ),
      concept(
        'trace-dependency',
        'Use traces to find the slow dependency',
        'Distributed traces and dependency latency show whether the time is in the app, DB, cache or a third party.',
        [
          'trace',
          'tracing',
          'span',
          'jaeger',
          'tempo',
          'opentelemetry',
          'downstream',
          'dependency',
          'apm',
        ],
        'Where is the time actually going, and what tells you?',
        { w: 3 },
      ),
      concept(
        'saturation',
        'Check saturation and the database',
        'Connection pool exhaustion, slow queries, locks, CPU throttling or GC are common causes.',
        [
          'connection pool',
          'slow quer',
          'lock',
          'throttl',
          'saturation',
          'gc',
          'cpu',
          'iops',
          'replication lag',
          'cache hit',
        ],
        'What resource limits could cause a slow-down without any code change?',
        { w: 3 },
      ),
      concept(
        'mitigation',
        'Mitigation options',
        'Scale out, shed load, disable a heavy feature, add a cache or fail over while root cause is pursued.',
        [
          'scale',
          'shed load',
          'rate limit',
          'feature flag',
          'disable',
          'failover',
          'restart',
          'cache',
          'mitigat',
        ],
        'It is hurting customers while you look. What can you do right now?',
        { w: 2 },
      ),
    ],
    redFlags: [
      redFlag(
        'restart-first',
        'Restart everything as a first move',
        [
          'restart everything',
          'restart all the',
          'first thing i would do is restart',
          'just restart',
          'reboot the servers',
        ],
        'What do you lose when you restart before gathering any evidence?',
        'Restarting first destroys the evidence you need to find the cause. Gather state, then decide.',
      ),
    ],
  }),
  question({
    id: 'ts-disk-full',
    rounds: ['troubleshooting'],
    topic: 'linux',
    technologies: ['linux'],
    difficulty: 'intermediate',
    prompt:
      'A production Linux host reports "No space left on device", but df shows plenty of free space. What could be wrong?',
    intent: 'A classic: inodes, deleted-but-open files, reserved blocks, mount layout.',
    expectedSignals: ['hypothesis', 'structured'],
    concepts: [
      concept(
        'inodes',
        'Inode exhaustion',
        'df -i shows inode use; millions of tiny files can exhaust inodes while bytes are free.',
        ['inode', 'df -i', 'small files', 'many files'],
        'Disk space is more than one number. What else can a filesystem run out of?',
        { w: 3 },
      ),
      concept(
        'deleted-open',
        'Deleted files still held open',
        'A deleted file keeps its space until the last process closes it (lsof +L1).',
        ['deleted', 'lsof', 'held open', 'open file', 'unlink', 'still open', 'truncate'],
        'You deleted a huge log but nothing was freed. Why?',
        { w: 3 },
      ),
      concept(
        'find-usage',
        'Find what is using space',
        'du -x, ncdu and per-mount checks locate large directories on the right filesystem.',
        ['du ', 'ncdu', 'largest', 'find / -size', 'which mount', 'which filesystem', 'df -h'],
        'How do you find what is actually filling the disk?',
        { w: 2 },
      ),
      concept(
        'mount-quota',
        'Check the right filesystem, quotas and reserved blocks',
        'The full path may be a separate mount, a quota, a container layer or reserved blocks.',
        ['mount', 'quota', 'reserved', 'overlay', 'tmpfs', 'docker', 'separate partition', 'lvm'],
        'Is the path you are writing to even on the filesystem you are looking at?',
        { w: 2 },
      ),
      concept(
        'root-cause-fix',
        'Fix the cause, not the symptom',
        'Rotate or ship logs, add alerting before 80%, and fix the producer.',
        [
          'logrotate',
          'rotate',
          'retention',
          'alert',
          'monitor',
          'prevent',
          'ship logs',
          'root cause',
        ],
        'Once it is back up, what keeps it from filling again?',
        { w: 2 },
      ),
    ],
  }),
  question({
    id: 'ts-cert-expiry',
    rounds: ['troubleshooting'],
    topic: 'security',
    technologies: ['tls', 'cert-manager', 'kubernetes', 'aws'],
    difficulty: 'senior',
    prompt:
      'At 02:00 a pager fires: customers cannot reach the API and a certificate expired. Walk me through the incident, then what you change afterwards.',
    intent:
      'Incident handling for a preventable outage: fast mitigation, communication, then systemic prevention.',
    expectedSignals: [...TS_SIGNALS, 'communication-plan', 'prevention'],
    maxFollowUps: 3,
    concepts: [
      concept(
        'confirm-impact',
        'Confirm and scope',
        'Verify the expiry with openssl or curl, identify every endpoint and certificate affected.',
        [
          'openssl',
          'curl -v',
          'verify',
          'which certificate',
          'all endpoints',
          'check the expiry',
          'confirm',
        ],
        'How do you confirm that is really the cause, and whether it is the only one?',
        { w: 3 },
      ),
      concept(
        'renew-deploy',
        'Renew and roll out the certificate',
        'Issue a new certificate (ACME, cert-manager, ACM) and deploy it, restarting or reloading where needed.',
        [
          'renew',
          'reissue',
          'cert-manager',
          'acme',
          "let's encrypt",
          'acm',
          'reload',
          'new certificate',
          'rotate',
        ],
        'What is the fastest safe way to get a valid certificate in front of customers?',
        { w: 3 },
      ),
      concept(
        'comms',
        'Communicate during the incident',
        'Status updates to customers and stakeholders, with a named incident owner.',
        [
          'status page',
          'communicat',
          'stakeholder',
          'incident commander',
          'update customers',
          'announce',
          'support team',
        ],
        'Who needs to know, and when?',
        { w: 2 },
      ),
      concept(
        'why-failed',
        'Why automation failed',
        'Find out why auto-renewal did not work: permissions, DNS challenge, a forgotten manual cert.',
        [
          'why did',
          'auto-renew',
          'renewal failed',
          'dns challenge',
          'manual certificate',
          'forgot',
          'owner',
        ],
        'This should not have been possible. How do you find out how it was?',
        { w: 2 },
      ),
      concept(
        'prevent-monitor',
        'Prevent with monitoring and inventory',
        'Expiry alerts at 30/14/7 days, a certificate inventory and blackbox probes.',
        [
          'expiry alert',
          'blackbox',
          'exporter',
          '30 days',
          'inventory',
          'monitor',
          'alert before',
          'synthetic',
        ],
        'What would have told you about this three weeks earlier?',
        { w: 3 },
      ),
      concept(
        'postmortem',
        'Blameless review',
        'A postmortem with actions and owners.',
        ['postmortem', 'post-mortem', 'blameless', 'retro', 'action items', 'review'],
        'How do you make sure the learning sticks?',
        { w: 1 },
      ),
    ],
  }),
]
